/*
 *
 * Courses constants
 *
 */

export const COURSE = 'COURSE';
export const COURSE_PENDING = 'COURSE_PENDING';
export const COURSE_FULFILLED = 'COURSE_FULFILLED';
export const COURSE_REJECTED = 'COURSE_REJECTED';

export const COURSE_DETAILS = 'COURSE_DETAILS';
export const COURSE_DETAILS_PENDING = 'COURSE_DETAILS_PENDING';
export const COURSE_DETAILS_FULFILLED = 'COURSE_DETAILS_FULFILLED';
export const COURSE_DETAILS_REJECTED = 'COURSE_DETAILS_REJECTED';

export const SEND_COMMENT_PENDING = 'SEND_COMMENT_PENDING';
export const SEND_COMMENT_FULFILLED = 'SEND_COMMENT_FULFILLED';
export const SEND_COMMENT_REJECTED = 'SEND_COMMENT_REJECTED';
