/*
 *
 * SessionDetails constants
 *
 */

export const SESSION_DETAILS = 'SESSION_DETAILS';
export const SESSION_DETAILS_PENDING = 'SESSION_DETAILS_PENDING';
export const SESSION_DETAILS_FULFILLED = 'SESSION_DETAILS_FULFILLED';
export const SESSION_DETAILS_REJECTED = 'SESSION_DETAILS_REJECTED';
