/*
 *
 * Articles constants
 *
 */

export const ARTICLES = 'ARTICLES';
export const ARTICLES_PENDING = 'ARTICLES_PENDING';
export const ARTICLES_FULFILLED = 'ARTICLES_FULFILLED';
export const ARTICLES_REJECTED = 'ARTICLES_REJECTED';
export const ARTICLES_DETAILS_PENDING = 'ARTICLES_DETAILS_PENDING';
export const ARTICLES_DETAILS_FULFILLED = 'ARTICLES_DETAILS_FULFILLED';
export const ARTICLES_DETAILS_REJECTED = 'ARTICLES_DETAILS_REJECTED';
