/*
 *
 * Signin constants
 *
 */

export const SEND_OTP = 'SEND_OTP';
export const SEND_OTP_PENDING = `${SEND_OTP}_PENDING`;
export const SEND_OTP_FULFILLED = `${SEND_OTP}_FULFILLED`;
export const SEND_OTP_REJECTED = `${SEND_OTP}_REJECTED`;

export const VERIFY_OTP = 'VERIFY_OTP';
export const VERIFY_OTP_PENDING = `${VERIFY_OTP}_PENDING`;
export const VERIFY_OTP_FULFILLED = `${VERIFY_OTP}_FULFILLED`;
export const VERIFY_OTP_REJECTED = `${VERIFY_OTP}_REJECTED`;

export const RESEND_OTP = 'RESEND_OTP';
export const RESEND_OTP_PENDING = `${RESEND_OTP}_PENDING`;
export const RESEND_OTP_FULFILLED = `${RESEND_OTP}_FULFILLED`;
export const RESEND_OTP_REJECTED = `${RESEND_OTP}_REJECTED`;

export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_PENDING = `${SIGN_IN}_PENDING`;
export const SIGN_IN_FULFILLED = `${SIGN_IN}_FULFILLED`;
export const SIGN_IN_REJECTED = `${SIGN_IN}_REJECTED`;

export const REGISTER = 'REGISTER';
export const REGISTER_PENDING = `${REGISTER}_PENDING`;
export const REGISTER_FULFILLED = `${REGISTER}_FULFILLED`;
export const REGISTER_REJECTED = `${REGISTER}_REJECTED`;

export const PROFILE_UPDATE = 'PROFILE_UPDATE';
export const PROFILE_UPDATE_PENDING = `${PROFILE_UPDATE}_PENDING`;
export const PROFILE_UPDATE_FULFILLED = `${PROFILE_UPDATE}_FULFILLED`;
export const PROFILE_UPDATE_REJECTED = `${PROFILE_UPDATE}_REJECTED`;
