/*
 *
 * Feedback constants
 *
 */

export const SEND_COMMENT_PENDING = 'SEND_COMMENT_PENDING';
export const SEND_COMMENT_FULFILLED = 'SEND_COMMENT_FULFILLED';
export const SEND_COMMENT_REJECTED = 'SEND_COMMENT_REJECTED';
