export const ENG = {
  app_name: 'Bima Paathshala',
  txt_submit: 'Submit',
  txt_education_made_easy: 'Education Made Easy',
  txt_company_name_copy: 'Company Name. All Rights Reserved.',
  txt_select_role: 'Select Role',
  txt_guru: 'Guru',
  txt_shishya: 'Shishya',
  txt_login: 'Login',
  txt_register: 'Register',
  txt_access_your_account: 'Access Your Account',
  txt_start_learning_marketing: 'Start Learning Finance Courses',
  txt_phone_number_comp: 'Phone Number *',
  txt_password_comp: 'Password *',
  txt_dont_have_account: "Don\\'t have an account?",
  txt_create_account: 'Create Account',
  txt_firstname_comp: 'First Name *',
  txt_lastname_comp: 'Last Name *',
  txt_email_address_comp: 'Email Address',
  txt_proceed: 'Proceed',
  txt_already_have_account: 'Already have an account?',
  txt_authentication_code: 'Authentication Code',
  txt_verifying_mobile_number: 'Verifying your mobile number',
  txt_resend_code: 'Resend Code in %s minute',
  txt_continue_registeration: 'Continue Registration',
  txt_pending_details: 'Pending Details',
  txt_gender: 'Gender',
  txt_male: 'Male',
  txt_female: 'Female',
  txt_occupation_comp: 'Occupation',
  txt_date_of_birth_comp: 'Date of Birth',
  txt_age_comp: 'Age',
  txt_mother_tongue_comp: 'Mother Tongue',
  txt_marital_status_comp: 'Marital Status',
  txt_dependent: 'Dependant',
  txt_address: 'Address',
  txt_locality: 'Locality/Post Office',
  txt_city: 'City/District/Region',
  txt_pin_code: 'Pin code *',
  txt_state: 'State',
  txt_search_learning_content: 'Search Courses',
  txt_courses: 'Courses',
  txt_see_all: 'See All',
  txt_videos: 'Videos',
  txt_articles: 'Articles',
  txt_home: 'Home',
  txt_upcoming_sessions: 'Upcoming Sessions',
  txt_attended_sessions: 'Attended Sessions',
  txt_certificates: 'Certificates',
  txt_refer_friend: 'Refer a Friend',
  txt_feedback: 'Feedback',
  txt_share: 'Share',
  txt_logout: 'Logout',
  txt_reviews: 'Reviews',
  txt_review: 'Review',
  txt_comments: 'Comments',
  txt_comment: 'Comment',
  txt_sessions: 'Sessions',
  txt_session: 'Session',
  txt_detail: 'Detail',
  txt_curriculum: 'Curriculum',
  txt_start_session: 'Start Session',
  txt_end_session: 'End Session',
  txt_search_shishya: 'Search Shishya',
  txt_add_new_shishya: 'Add New Shishya',
  txt_add_shishya: 'Add Shishya',
  txt_cancel: 'Cancel',
  txt_shishya_will_be_joining: 'Shishya will be joining the session',
  txt_brief: 'Brief',
  txt_quiz: 'Quiz',
  txt_certificate: 'Certificate',
  txt_add_new_comment: 'Comment',
  txt_close: 'Close',
  txt_download_certificate: 'Download Certificate',
  txt_next_que: 'Next Question',
  txt_submit_answer: 'Submit Answers',
  txt_try_again: "Try Again, you\\'ll probably get it right next time.",
  txt_another_attempt: 'Another Attempt',
  txt_results: 'Results',
  txt_upcoming_session: 'Upcoming Sessions',
  txt_completed_session: 'Completed Sessions',
  txt_expense_manager: 'Expense Manager',
  txt_expenses: 'Expenses',
  txt_documents: 'Documents',
  txt_upcoming: 'Upcoming',
  txt_attended: 'Attended',
  txt_submit_feedback: 'Submit Feedback',
  txt_text: 'Text',
  txt_audio: 'Audio',
  txt_video: 'Video',
  txt_my_profile: 'My Profile',
  txt_basic_info: 'Basic Info',
  txt_more_info: 'More Info',
  txt_update_info: 'Update Info',
  txt_choose_language: 'Choose Language',
  txt_english: 'English',
  txt_choose_role: 'Choose Role',
  txt_adhar_card_no: 'Aadhar Card No*',
  txt_referral_code: 'Referral Code',
  txt_pay_and_subscribe: 'Pay and Subscribe %s',
  txt_next_question: 'Next Question',
  txt_yes_want_to_exit: 'Yes, I want to exit',
  txt_congratulations: 'Congrats!',
  txt_succesfully_completed_course:
    'Well done.You have successfully completed this section of the course %s.',
  txt_write_your_feedback_here: 'Please share your feedback here.',
  txt_search_expense: 'Search Expense',
  txt_export: 'Export',
  txt_add_new_expense: 'Add new Expense',
  txt_expense_will_be_verified: 'Expense added is yet to be verified.',
  txt_expense_title_com: 'Expense Title *',
  txt_date_time_com: 'Date and Time *',
  txt_amount_com: 'Amount *',
  txt_expense_category_com: 'Expense Category',
  txt_add_expense: 'Add Expense',
  txt_pending: 'Pending',
  txt_verified_shishya: 'Verified Shishya',
  txt_upload: 'Upload',
  txt_adhar_card: 'Aadhar Card',
  txt_start_day: 'Start Day',
  txt_end_day: 'End Day',
  txt_chat_with_guru: 'Chat with Guru',
  txt_guru_shishya_chat: 'Guru and Shishya Chat',
  txt_my_attendance_log: 'My Attendance Log',
  txt_refer_a_friend: 'Refer a Friend',
  txt_font_size_settings: 'Font Settings',
  txt_leaderboard: 'Leader Board',
  txt_account: 'Account',
  txt_got_it: 'Got It',
  txt_verification_status: 'Verification Status',
  txt_upload_bill: 'Upload Bill',
  navigation_drawer_open: 'Open',
  navigation_drawer_close: 'Close',
  txt_view: 'View',
  txt_download: 'Download',
  txt_notification: 'Notifications',
  txt_help: 'Help',
  txt_queries_response: 'Queries and Responses',
  txt_course_details: 'Course Details',
  txt_start: 'Start',
  txt_my_shishya: 'My Shishya',
  txt_approved: 'Approved',
  txt_sent_back: 'Sent Back',
  txt_completed: 'Completed',
  txt_session_detail: 'Session Detail',
  txt_take_attendance: 'Take Attendance',
  txt_feedback_desc:
    'We would love to know what you think about us. Please write to us and share your feedback.',
  txt_refer: 'Refer',
  txt_copy: 'Copy',
  txt_settings: 'Settings',
  txt_select_district_wise: 'Select District Wise',
  txt_search_queries: 'Search Queries',
  txt_search_sessions: 'Search Sessions',
  txt_search_by_date: 'Search by Date',
  txt_shishy_list: 'Shishya List',
  txt_expenses_total: 'Expenses Total',
  txt_sent_back_expenses: 'Sent Back Expenses',
  txt_sent_back_expenses_total: 'Sent Back Expenses Total',
  txt_pending_expenses: 'Pending Expenses',
  txt_pending_expenses_total: 'Pending Expenses Total',
  txt_some_thing_wrong: 'Oops!Something went wrong. Please try again later.',
  txt_unable_to_connect:
    'Sorry, we are unable to connect with the server. Please try again later.',
  txt_type_your_message_here: 'Type your message here...',
  txt_contact_support: 'Contact Support',
  txt_go_back: 'Go Back',
  txt_account_deactivated: 'Account Deactivated',
  txt_can_not_attempt_login: 'Cannot attempt Login.Please contact support.',
  txt_failed_course_message:
    'Unfortunately, you have failed to complete the course assessment. We urge you to re-attempting the assesment to get a certificate.',
  txt_next_section: 'Go to Next Section',
  txt_rate_exp: 'RATE YOUR EXPERIENCE',
  txt_skip: 'Skip',
  txt_result_congratulations: 'Congrats!',
  txt_sample_text: 'Sample Text',
  txt_sample_text_desc: 'The quick brown fox jumps over the lazy dog.',
  txt_no_internet_connection: 'Please check you Internet Connection.',
  txt_please_wait: 'Please wait...',
  txt_save_settings: 'Save Settings',
  txt_hindi: 'हिन्दी',
  txt_marathi: 'मराठी',
  txt_tamil: 'தமிழ்',
  txt_save_font_settings: 'Save Font Size',
  txt_setting_saved: 'Settings saved successfully.',
  txt_ratings: 'Ratings',
  txt_please_fill_all_details: '"Please fill all detail. "',
  txt_sections: 'Sections',
  txt_assessments: 'Assessments',
  txt_section: 'Section',
  txt_assessment: 'Assessment',
  txt_courses_listed: 'Courses listed',
  txt_articles_listed: 'Articles listed',
  txt_videos_listed: 'Videos listed',
  txt_course_listed: 'Course listed',
  txt_article_listed: 'Article listed',
  txt_video_listed: 'Video listed',
  txt_user_details_not_found: 'User details not found. Please Login again.',
  txt_sessions_listed: 'Sessions',
  txt_session_listed: 'Session',
  txt_shishya_going_to_attend_session:
    'Shishya are going to attend this session',
  txt_shishyas_going_to_attend_session:
    'Shishyas are going to attend this session',
  txt_roll_no: '"Roll No : "',
  txt_attendance_logged_msg:
    "Your attendance has been logged. Please click on \\'END DAY\\' after your day is over.",
  txt_start_session_msg:
    "You have started the session. Please click on \\'END SESSION\\' to save your attendance",
  txt_please_grant_all_permission: 'Please grant permission.',
  txt_gujrati: 'ગુજરાતી',
  txt_malyalam: 'മലയാളം',
  txt_choose_language_converted: 'Choose Language',
  txt_language_settings: 'Language Settings',
  media_picker_select_from: 'Select From',
  media_picker_camera: 'Camera',
  media_picker_gallery: 'Gallery',
  media_picker_ok: 'Ok',
  media_picker_cancel: 'Cancel',
  media_picker_some_permission_is_denied: 'Please grant permission.',
  media_picker_you_need_to_grant_access_to: 'You need to grant access to',
  media_picker_read_Write_external_storage: 'Read and Write External Storage',
  txt_choose_photo: 'Choose Photo',
  txt_duration: '"Duration : "',
  txt_guru_name: '"Guru name : "',
  txt_course_duration: '"Duration : "',
  txt_choose: 'Choose',
  txt_from_gallery: 'From Gallery',
  txt_from_camera: 'From Camera',
  txt_update_language: 'Update Language',
  txt_choose_language_convenience: 'Please choose your preffered language.',
  txt_minutes: 'Minutes',
  txt_questions: 'Questions',
  txt_question: 'Question',
  txt_please_give_answer: 'Please Choose Answer',
  txt_time_left: '"Time Left : "',
  txt_time_up: 'Time Up',
  txt_mins: 'Mins',
  txt_quit_quiz:
    '"If you quit the exam, you won\'t be qualified to attempt the next section "',
  title_activity_maps: 'Map',
  txt_downloading_certificate: 'Downloading Certificate.',
  txt_you_have_started_session:
    'You have started the session, Click on END SESSION to save attendance',
  txt_no_shishya_for_attendance: 'No Shishya selected for attendance.',
  txt_no_shishya_available: 'No Shishya available.',
  txt_choose_video: 'Choose Video',
  txt_chat: 'Chat',
  txt_curriculum_not_available: 'Curriculum not available.',
  txt_shishya_not_available: 'Shishya not available.',
  txt_rs: '"₹ "',
  error_message_url_not_valid: 'Video URL is not valid.',
  txt_this_content_is_downloaded: 'This is already downloaded.',
  txt_unable_to_downloaded:
    'Sorry, we are unable to download this file. Please try again later. ',
  txt_download_success: 'File downloaded successfully!',
  txt_downloading_media: 'Downloading Files.',
  txt_approved_expenses: 'Approved Expenses',
  txt_description: 'Description',
  txt_date: 'Date',
  txt_amount: 'Amount',
  txt_total_amount: '"Total Amount "',
  txt_details_saved_on_local_storage: 'Details are saved in your storage.',
  txt_details_not_saved:
    'Sorry, we are unable to save details in your storage.',
  txt_sync_with_server: 'Sync Data',
  txt_based_on_reviews: 'based on %s reviews.',
  txt_based_on_review: 'based on %s review.',
  txt_user_details_not_available: 'User details are not available.',
  txt_data_not_available: 'No data available.',
  txt_shishya_under_guidance: 'Shishya are enrolled under your guidance',
  txt_shishyas_under_guidance: 'Shishyas are enrolled under your guidance',
  txt_yes: 'Yes',
  txt_logout_msg: 'Are you sure you want to logout?',
  txt_copied_to_clipboard: 'Copied to clipboard.',
  txt_refer_message:
    '"Hey there, here\'s an extremely educative APP that will be useful to you. Please install it and use this referral code : "',
  txt_share_message:
    '"Hey there, here\'s an extremely educative APP that will be useful to you. Please install it."',
  txt_course_completed: 'Course Completed.',
  txt_please_record_audio: 'Please record audio.',
  txt_please_record_video: 'Please select or record a video.',
  txt_revie_submitted: 'Review Submitted.',
  txt_this_content_is_updated: 'Content updated successfully.',
  default_notification_channel_id: 'bimapaathshala_channel',
  fcm_message: 'New Message',
  txt_search_guru: 'Search Guru',
  txt_guru_list: 'Guru List',
  txt_guru_under_guidance: 'Guru',
  txt_gurus_under_guidance: 'Gurus',
  txt_my_guru: 'My Guru',
  txt_please_enter_mobile_number: 'Please enter your mobile number.',
  txt_please_enter_valid_mobile_number:
    'Please enter your valid mobile number.',
  txt_please_enter_firstname: 'Please enter your first name.',
  txt_please_enter_last_name: 'Please enter your last name.',
  txt_please_enter_adharcard_no: 'Please enter Aadhar Card no.',
  txt_please_enter_valid_adharcard_no: 'Please enter valid Aadhar Card no.',
  txt_please_enter_email_address: 'Please enter email address.',
  txt_please_enter_valid_email_address: 'Please enter valid email address.',
  txt_please_enter_occupation: 'Please enter Occupation.',
  txt_please_enter_date_of_birth: 'Please enter Date of Birth.',
  txt_please_enter_age: 'Please enter your Age.',
  txt_please_enter_marital_status: 'Please enter your Marital status.',
  txt_enter_otp: 'Please enter OTP.',
  txt_enter_digit_otp: 'Please enter OTP.',
  txt_resend: 'Resend Code',
  txt_choose_profile_pic: 'Choose a Profile Picture.',
  txt_choose_adhar_card: 'Choose a Aadhar Card Photo',
  txt_till_: 'Till %s',
  txt_no_internet_exam_msg:
    'You will need to have an active internet connection in order to give the  examination.',
  txt_please_enter_title: 'Please enter title.',
  txt_please_enter_date_time: 'Please enter Date and Time.',
  txt_please_enter_amount: 'Please enter amount.',
  txt_please_enter_category: 'Please enter Expense Category.',
  txt_choose_bill: 'Please choose bill.',
  txt_please_enter_valid_adharcard: 'Please enter Aadhar Card.',
  txt_no_viewer_to_view_file: 'There is no viewer to view this file.',
  txt_unable_to_create_channel: 'Unable to create channel.',
  txt_shishya_list: 'Shishya List',
  no_notifications: 'No notification data available.',
  no_notifications_msg: 'No notification available.',
  no_upcoming_session: 'No Upcoming Session',
  no_completed_session: 'No Completed Session.',
  no_certificate_message:
    'You have no certificates yet. Please complete a course in order to get a certificate.',
  no_expense_data: 'Expense data not available.',
  no_attendance_log: 'Attendance log not available.',
  txt_new_message: 'New Message From',
  txt_welcome: 'Welcome',
  txt_data_not_available_leaderboard:
    'You could be the first one on the leaderboard, hurry up and pass our assessments now!',
  txt_please_wait_for_internet_to_upload_bill:
    'You cannot upload a bill when you are offline. Try again later.',
  txt_ok: 'OK',
  txt_time_over_message: 'Time is up. Good try.',
  txt_record: 'Record',
  txt_stop_record: 'Stop Recording',
  txt_play: 'Play',
  txt_stop: 'Stop',
  txt_review_submitted: 'Review Submitted.',
  txt_view_courses: 'View Courses',
  txt_choose_country: 'Choose Country',
  txt_india: 'India',
  txt_south_africa: 'South Africa',
  txt_sri_lanka: 'Sri Lanka',
  txt_bangladesh: 'Bangladesh',
  txt_indonesia: 'Indonesia',
  txt_session_detail_updated: 'Session details updated successfully.',
  txt_session_download_success: 'Session details downloaded successfully.',
  txt_article_updated: 'Article details updated successfully.',
  txt_article_download: 'Article details downloaded successfully.',
  txt_video_updated: 'Video details updated successfully.',
  txt_video_download: 'Video details downloaded successfully.',
  txt_course_updated: 'Course details updated successfully.',
  txt_course_download: 'Course details downloaded successfully.',
  txt_no_expense_data_available_to_export:
    'There is no expense data to export.',
  txt_no_attendance_to_export: 'There is no attendance data to export.',
  txt_sync_started_with_server: 'Sync started with server.',
  txt_recording: 'Recording Playing.',
  txt_recording_stopped: 'Recording stopped.',
  txt_recording_started: 'Recording started.',
  txt_please_complete_section:
    'Please complete section to unlock the next one.',
  txt_pending_assessment: 'Pending Assessment',
  txt_otp_retry_failed: 'OTP sending failed.',
  txt_otp_retry_success: 'OTP sent successfully.',
  txt_invalid_otp: 'Please enter a valid OTP.',
  txt_unable_to_send_review: 'Unable to submit review.',
  txt_unable_to_submit_quiz: 'Unable to submit quiz.',
  txt_no_assessment: 'We are unable to fetch assessment details.',
  txt_no_data_available: 'No data available.',
  txt_unable_to_register: 'Sorry we are unable to register your account.',
  txt_unable_to_update_account: 'Sorry we are unable to update your details.',
  txt_shishyas_course_watch_counter: '%s shishyas have watched this course.',
  txt_shishya_course_watch_counter: '%s shishya have watched this course.',
  txt_shishya_are_attending_session: '%s shishya are attending session.',
  txt_shishyas_are_attending_session: '%s shishyas are attending session.',
  txt_profile_updated: 'Profile updated successfully.',
  txt_data_not_available_session: 'Session data not available',
  no_article_message: 'No article available.',
  no_course_message: 'No course available.',
  no_video_message: 'No video available',
  txt_session_end_successfully: 'Session ended successfully.',
  txt_session_end_failed: 'Unable to end session.',
  txt_to_be_launched_soon: 'To be Launched Soon',
  txt_you_can_not_start_day_again: "You can not \\'Start Day\\' again.",
  txt_view_more: 'View More',
  txt_view_less: 'View Less',
  txt_difficult_to_understand: 'Difficult to understand.',
  txt_too_fast: 'Too fast.',
  txt_other: 'Other',
  txt_shishya_already_added_session:
    'This shishya is already added to session.',
  txt_no_match_found: 'No match found.',
  txt_expenses_added_success: 'Expense added successfully.',
  txt_expenses_added_failed: 'Unable to add expense.',
  txt_shishya_already_added: 'Shishya is already added.',
  txt_shishya_have_attend_session: 'Shishya have attended this session',
  txt_shishyas_have_attend_session: 'Shishyas have attended this session',
  txt_can_not_start_session_zero_shishya:
    'There is no shishya added to this session so you can not start session.',
  txt_pending_assessment_message: 'To unlock next %s Please watch %s.',
  txt_it_seems_sanchalak:
    'It seems that your details are registered as sanchalak. Please contact admin.',
  no_attended_session: 'No attended session.',
  txt_add_more_details: 'Add more details',
  txt_please_enter_valid_pincode: 'Please enter valid pincode.',
  txt_please_enter_pincode: 'Please enter pincode.',
  txt_can_not_start_session_before_date:
    'You can not start session before session date.',
  txt_video_not_available: 'Video not available.',
  txt_audio_not_available: 'Audio not available.',
  txt_file_not_available: 'File not available.',
  font_size: ['Small', 'Medium', 'Large', 'Extra Large'],
  occupation: [
    'Farmer',
    'Accountant',
    'Driver',
    'Cleaner',
    'Construction labour',
    'Student',
    'Fisherman',
    'Nurse',
    'Office clerk',
    'Salesperson',
    'Sewing machine operator',
    'Shopkeeper',
    'Tailor',
    'Teacher',
    'Vegetable harvester',
    'Vegetable picker',
    'Waiter',
    'Other',
  ],
  dependent: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
  maritalstatus: ['Married', 'Unmarried'],
  mothertonge: ['Hindi', 'English', 'Gujarati', 'Marathi', 'Others'],
  expense_category: ['Travel', 'Food', 'Others'],
};
