export const GUJ = {
  app_name: 'બીમા પાઠશાળા',
  txt_submit: 'સબમિટ કરો',
  txt_education_made_easy: 'શિક્ષણ સરળ બનાવ્યું',
  txt_company_name_copy: 'કંપનીનું નામ. બધા હકો અમારી પાસે રાખેલા છે.',
  txt_select_role: 'ભૂમિકા પસંદ કરો',
  txt_guru: 'ગુરુ',
  txt_shishya: 'શિષ્ય્યા',
  txt_login: 'પ્રવેશ કરો',
  txt_register: 'નોંધણી કરો',
  txt_access_your_account: 'તમારું એકાઉન્ટ ઍક્સેસ કરી',
  txt_start_learning_marketing: 'ફાઇનાન્સ અભ્યાસક્રમો શીખવાનું પ્રારંભ કરો',
  txt_phone_number_comp: 'ફોન નંબર *',
  txt_password_comp: 'પાસવર્ડ *',
  txt_dont_have_account: 'શું તમારું ખાતું નથી?',
  txt_create_account: 'એકાઉન્ટ બનાવો',
  txt_firstname_comp: 'પ્રથમ નામ *',
  txt_lastname_comp: 'છેલ્લું નામ *',
  txt_email_address_comp: 'ઇમેઇલ સરનામું',
  txt_proceed: 'આગળ વધો',
  txt_already_have_account: 'પહેલેથી જ એક એકાઉન્ટ છે?',
  txt_authentication_code: 'પ્રમાણીકરણ કોડ',
  txt_verifying_mobile_number: 'તમારો મોબાઇલ નંબર ચકાસી રહ્યો છે',
  txt_resend_code: '%s મિનિટમાં કોડ ફરીથી મોકલો',
  txt_continue_registeration: 'નોંધણી ચાલુ રાખો',
  txt_pending_details: 'બાકી વિગતો',
  txt_gender: 'લિંગ',
  txt_male: 'પુરુષ',
  txt_female: 'સ્ત્રી',
  txt_occupation_comp: 'વ્યવસાય',
  txt_date_of_birth_comp: 'જન્મ તારીખ',
  txt_age_comp: 'ઉંમર',
  txt_mother_tongue_comp: 'માતૃભાષા',
  txt_marital_status_comp: 'વૈવાહિક સ્થિતિ',
  txt_dependent: 'આશ્રિત',
  txt_address: 'સરનામું',
  txt_locality: 'વિસ્તાર / પોસ્ટ ઓફિસ',
  txt_city: 'શહેર / જિલ્લા / ક્ષેત્ર',
  txt_pin_code: 'પિન કોડ *',
  txt_state: 'રાજ્ય',
  txt_search_learning_content: 'શોધ અભ્યાસક્રમો',
  txt_courses: 'અભ્યાસક્રમો',
  txt_see_all: 'બધા જુઓ',
  txt_videos: 'વિડિઓઝ',
  txt_articles: 'લેખ',
  txt_home: 'ઘર',
  txt_upcoming_sessions: 'આવનારા સત્રો',
  txt_attended_sessions: 'સત્રોમાં ભાગ લીધો',
  txt_certificates: 'પ્રમાણપત્રો',
  txt_refer_friend: 'મિત્ર નો સંદર્ભ લો',
  txt_feedback: 'પ્રતિસાદ',
  txt_share: 'શેર કરો',
  txt_logout: 'લૉગ આઉટ',
  txt_reviews: 'સમીક્ષાઓ',
  txt_review: 'સમીક્ષા',
  txt_comments: 'ટિપ્પણીઓ',
  txt_comment: 'ટિપ્પણી',
  txt_sessions: 'સત્રો',
  txt_session: 'સત્ર',
  txt_detail: 'વિગતવાર',
  txt_curriculum: 'અભ્યાસક્રમ',
  txt_start_session: 'સત્ર પ્રારંભ કરો',
  txt_end_session: 'સત્ર સમાપ્ત થાય છે',
  txt_search_shishya: 'શિષ્ય શોધ',
  txt_add_new_shishya: 'નવું શિષ્ય ઉમેરો',
  txt_add_shishya: 'શિષ્ય ઉમેરો',
  txt_cancel: 'રદ કરો',
  txt_shishya_will_be_joining: 'શિષ્ય સત્રમાં જોડાશે',
  txt_brief: 'સંક્ષિપ્ત',
  txt_quiz: 'ક્વિઝ',
  txt_certificate: 'પ્રમાણપત્ર',
  txt_add_new_comment: 'ટિપ્પણી',
  txt_close: 'બંધ',
  txt_download_certificate: 'પ્રમાણપત્ર ડાઉનલોડ કરો',
  txt_next_que: 'આગળનો પ્રશ્ન',
  txt_submit_answer: 'જવાબો સબમિટ કરો',
  txt_try_again: 'ફરીથી પ્રયાસ કરો, તમને તે કદાચ આગલી વખતે મળી જશે.',
  txt_another_attempt: 'બીજો પ્રયાસ',
  txt_results: 'પરિણામો',
  txt_upcoming_session: 'આવનારા સત્રો',
  txt_completed_session: 'પૂર્ણ થયેલા સત્રો',
  txt_expense_manager: 'ખર્ચ વ્યવસ્થાપક',
  txt_expenses: 'ખર્ચ',
  txt_documents: 'દસ્તાવેજો',
  txt_upcoming: 'આગામી',
  txt_attended: 'જોડાયા',
  txt_submit_feedback: 'પ્રતિસાદ સબમિટ કરો',
  txt_text: 'ટેક્સ્ટ',
  txt_audio: 'ઓડિયો',
  txt_video: 'વિડિઓ',
  txt_my_profile: 'મારી પ્રોફાઇલ',
  txt_basic_info: 'મૂળભૂત માહિતી',
  txt_more_info: 'વધુ માહિતી',
  txt_update_info: 'અપડેટ માહિતી',
  txt_choose_language: 'Choose Language',
  txt_english: 'અંગ્રેજી',
  txt_choose_role: 'ભૂમિકા પસંદ કરો',
  txt_adhar_card_no: 'આધારકાર્ડ નંબર *',
  txt_referral_code: 'રેફરલ કોડ',
  txt_pay_and_subscribe: 'ચૂકવણી કરો અને %s સબ્સ્ક્રાઇબ કરો',
  txt_next_question: 'આગળનો પ્રશ્ન',
  txt_yes_want_to_exit: 'હા, હું બહાર નીકળવા માંગુ છું',
  txt_congratulations: 'અભિનંદન!',
  txt_succesfully_completed_course:
    'સરસ. તમે %s કોર્સનો આ વિભાગ સફળતાપૂર્વક પૂર્ણ કરી લીધો છે.',
  txt_write_your_feedback_here: 'કૃપા કરીને તમારા પ્રતિસાદ અહીં શેર કરો.',
  txt_search_expense: 'શોધ ખર્ચ',
  txt_export: 'નિકાસ',
  txt_add_new_expense: 'નવો ખર્ચ ઉમેરો',
  txt_expense_will_be_verified: 'ખર્ચ ઉમેર્યો તે ચકાસવાનું બાકી છે.',
  txt_expense_title_com: 'ખર્ચ શીર્ષક *',
  txt_date_time_com: 'તારીખ અને સમય *',
  txt_amount_com: 'રકમ *',
  txt_expense_category_com: 'ખર્ચ વર્ગ',
  txt_add_expense: 'ખર્ચ ઉમેરો',
  txt_pending: 'બાકી',
  txt_verified_shishya: 'ચકાસાયેલ શિષ્ય્યા',
  txt_upload: 'અપલોડ કરો',
  txt_adhar_card: 'આધારકાર્ડ',
  txt_start_day: 'પ્રારંભ દિવસ',
  txt_end_day: 'અંતિમ દિવસ',
  txt_chat_with_guru: 'ગુરુ સાથે ગપસપ',
  txt_guru_shishya_chat: 'ગુરુ અને શિષ્ય ચેટ',
  txt_my_attendance_log: 'મારી હાજરી લોગ',
  txt_refer_a_friend: 'મિત્રનો સંદર્ભ લો',
  txt_font_size_settings: 'ફોન્ટ સેટિંગ્સ',
  txt_leaderboard: 'નેતા મંડળ',
  txt_account: 'એકાઉન્ટ',
  txt_got_it: 'સમજાયું',
  txt_verification_status: 'ચકાસણીની સ્થિતિ',
  txt_upload_bill: 'બિલ અપલોડ કરો',
  navigation_drawer_open: 'ખુલ્લું',
  navigation_drawer_close: 'બંધ',
  txt_view: 'જુઓ',
  txt_download: 'ડાઉનલોડ',
  txt_notification: 'સૂચનાઓ',
  txt_help: 'સહાય',
  txt_queries_response: 'પ્રશ્નો અને જવાબો',
  txt_course_details: 'કોર્સ વિગતો',
  txt_start: 'પ્રારંભ કરો',
  txt_my_shishya: 'મારું શિષ્ય',
  txt_approved: 'મંજૂર',
  txt_sent_back: 'મોકલેલો',
  txt_completed: 'પૂર્ણ',
  txt_session_detail: 'સત્ર વિગત',
  txt_take_attendance: 'હાજરી લો',
  txt_feedback_desc:
    'તમે અમારા વિશે શું વિચારો છો તે જાણવાનું અમને ગમશે. કૃપા કરીને અમને લખો અને તમારો પ્રતિસાદ શેર કરો.',
  txt_refer: 'નો સંદર્ભ લો',
  txt_copy: 'નકલ',
  txt_settings: 'સેટિંગ્સ',
  txt_select_district_wise: 'જિલ્લા મુજબની પસંદ કરો',
  txt_search_queries: 'ક્વેરીઝ શોધો',
  txt_search_sessions: 'સત્રો શોધો',
  txt_search_by_date: 'તારીખ દ્વારા શોધો',
  txt_shishy_list: 'શિષ્ય સૂચિ',
  txt_expenses_total: 'ખર્ચ કુલ',
  txt_sent_back_expenses: 'પાછા ખર્ચ મોકલ્યો',
  txt_sent_back_expenses_total: 'મોકલેલ પાછળ ખર્ચ',
  txt_pending_expenses: 'બાકી ખર્ચ',
  txt_pending_expenses_total: 'બાકી ખર્ચ કુલ',
  txt_some_thing_wrong: 'અરેરે! કંઈક ખોટું થયું પછીથી ફરી પ્રયત્ન કરો.',
  txt_unable_to_connect:
    'માફ કરશો, અમે સર્વર સાથે જોડાવા માટે અસમર્થ છીએ. પછીથી ફરી પ્રયત્ન કરો.',
  txt_type_your_message_here: 'તમારો સંદેશ અહીં લખો...',
  txt_contact_support: 'સંપર્ક સપોર્ટ',
  txt_go_back: 'પાછા જાઓ',
  txt_account_deactivated: 'એકાઉન્ટ નિષ્ક્રિય',
  txt_can_not_attempt_login:
    'લોગીન નો પ્રયાસ કરી શકાતો નથી. કૃપા કરીને સપોર્ટનો સંપર્ક કરો.',
  txt_failed_course_message:
    'દુર્ભાગ્યે, તમે કોર્સ આકારણી પૂર્ણ કરવામાં નિષ્ફળ ગયા છો. અમે તમને પ્રમાણપત્ર મેળવવા માટે મૂલ્યાંકન ફરીથી કરવાનો પ્રયાસ કરવા વિનંતી કરીએ છીએ.',
  txt_next_section: 'આગલા વિભાગ પર જાઓ',
  txt_rate_exp: 'તમારી અનુભવને રેટ કરો',
  txt_skip: 'અવગણો',
  txt_result_congratulations: 'અભિનંદન!',
  txt_sample_text: 'નમૂના ટેક્સ્ટ',
  txt_sample_text_desc: 'ઝડપી બ્રાઉન શિયાળ આળસુ કૂતરા ઉપર કૂદી પડ્યું.',
  txt_no_internet_connection: 'કૃપા કરીને ઇન્ટરનેટ કનેક્શન તપાસો.',
  txt_please_wait: 'કૃપા કરી પ્રતીક્ષા કરો ...',
  txt_save_settings: 'સેટિંગ્સ સાચવો',
  txt_hindi: 'હિન્દી',
  txt_marathi: 'મરાઠી',
  txt_tamil: 'தமிழ்',
  txt_save_font_settings: 'ફોન્ટ નું કદ સાચવો',
  txt_setting_saved: 'સેટિંગ્સ સફળતાપૂર્વક સાચવવામાં આવી.',
  txt_ratings: 'રેટિંગ્સ',
  txt_please_fill_all_details: '"કૃપા કરીને બધી વિગત ભરો."',
  txt_sections: 'વિભાગો',
  txt_assessments: 'આકારણીઓ',
  txt_section: 'કલમ',
  txt_assessment: 'આકારણી',
  txt_courses_listed: 'અભ્યાસક્રમો સૂચિબદ્ધ',
  txt_articles_listed: 'લેખ સૂચિબદ્ધ',
  txt_videos_listed: 'વિડિઓઝ સૂચિબદ્ધ',
  txt_course_listed: 'કોર્સ સૂચિબદ્ધ',
  txt_article_listed: 'લેખ સૂચિબદ્ધ ',
  txt_video_listed: 'વિડિઓ સૂચિબદ્ધ',
  txt_user_details_not_found:
    'વપરાશકર્તા વિગતો મળી નથી. કૃપા કરીને લ .ગિન કરો.',
  txt_sessions_listed: 'સત્રો',
  txt_session_listed: 'સત્ર',
  txt_shishya_going_to_attend_session: 'શિષ્ય આ સત્રમાં ભાગ લેવા જઇ રહ્યા છે',
  txt_shishyas_going_to_attend_session: 'શિષ્ય આ સત્રમાં ભાગ લેવા જઇ રહ્યા છે',
  txt_roll_no: '"રોલ નંબર: "',
  txt_attendance_logged_msg:
    'તમારી હાજરી રજીસ્ટર થઈ ગઈ છે. કૃપા કરી તમારો દિવસ સમાપ્ત થયા પછી અંત દિન પર ક્લિક કરો.',
  txt_start_session_msg:
    'તમે સત્ર શરૂ કર્યું છે. કૃપા કરીને તમારી હાજરી બચાવવા માટે અંત સત્ર પર ક્લિક કરો',
  txt_please_grant_all_permission: 'કૃપા કરીને મંજૂરી આપો.',
  txt_gujrati: 'ગુજરાતી',
  txt_malyalam: 'മലയാളം',
  txt_choose_language_converted: 'ભાષા પસંદ કરો',
  txt_language_settings: 'ભાષા સેટિંગ્સ',
  media_picker_select_from: 'માંથી પસંદ કરો',
  media_picker_camera: 'કેમેરા',
  media_picker_gallery: 'ગેલેરી',
  media_picker_ok: 'ઓકે',
  media_picker_cancel: 'રદ કરો',
  media_picker_some_permission_is_denied: 'કૃપા કરીને મંજૂરી આપો.',
  media_picker_you_need_to_grant_access_to: 'તમારે આની ઍક્સેસ આપવાની જરૂર છે',
  media_picker_read_Write_external_storage: 'બાહ્ય સ્ટોરેજ વાંચો અને લખો',
  txt_choose_photo: 'ફોટો પસંદ કરો',
  txt_duration: '"અવધિ: "',
  txt_guru_name: '"ગુરુ નામ: "',
  txt_course_duration: '"અવધિ: "',
  txt_choose: 'પસંદ કરો',
  txt_from_gallery: 'ગેલેરી માંથી ',
  txt_from_camera: 'કેમેરા માંથી',
  txt_update_language: 'ભાષા અપડેટ કરો',
  txt_choose_language_convenience: 'કૃપા કરી તમારી પ્રેફરર્ડ ભાષા પસંદ કરો.',
  txt_minutes: 'મિનિટ',
  txt_questions: 'પ્રશ્નો',
  txt_question: 'પ્રશ્ન',
  txt_please_give_answer: 'કૃપા કરીને જવાબ પસંદ કરો',
  txt_time_left: '"સમય બાકી: "',
  txt_time_up: 'સમય સમાપ્ત',
  txt_mins: 'મિનિટ',
  txt_quit_quiz:
    '"જો તમે પરીક્ષા છોડી દો છો, તો તમે આગલા વિભાગને અજમાવવા માટે લાયક છો નહીં"',
  title_activity_maps: 'નકશો',
  txt_downloading_certificate: 'પ્રમાણપત્ર ડાઉનલોડ કરી રહ્યું છે.',
  txt_you_have_started_session:
    'તમે સત્ર શરૂ કર્યું છે, હાજરી બચાવવા માટે અંત સત્ર પર ક્લિક કરો',
  txt_no_shishya_for_attendance: 'કોઈ શિષ્ય હાજરી માટે પસંદ થયેલ નથી.',
  txt_no_shishya_available: 'કોઈ શિષ્ય ઉપલબ્ધ નથી.',
  txt_choose_video: 'વિડિઓ પસંદ કરો',
  txt_chat: 'ગપસપ',
  txt_curriculum_not_available: 'અભ્યાસક્રમ ઉપલબ્ધ નથી.',
  txt_shishya_not_available: 'શિષ્ય ઉપલબ્ધ નથી.',
  txt_rs: '"₹"',
  error_message_url_not_valid: 'વિડિઓ URL માન્ય નથી.',
  txt_this_content_is_downloaded: 'આ પહેલેથી ડાઉનલોડ થયેલ છે.',
  txt_unable_to_downloaded:
    'માફ કરશો, અમે આ ફાઇલ ડાઉનલોડ કરવામાં અસમર્થ છીએ. પછીથી ફરી પ્રયત્ન કરો.',
  txt_download_success: 'ફાઇલ સફળતાપૂર્વક ડાઉનલોડ થઈ!',
  txt_downloading_media: 'ફાઇલો ડાઉનલોડ કરી રહ્યાં છે.',
  txt_approved_expenses: 'માન્ય ખર્ચ',
  txt_description: 'વર્ણન',
  txt_date: 'તારીખ',
  txt_amount: 'રકમ',
  txt_total_amount: '"કુલ રકમ"',
  txt_details_saved_on_local_storage:
    'વિગતો તમારા સ્ટોરેજમાં સાચવવામાં આવી છે.',
  txt_details_not_saved:
    'માફ કરશો, અમે તમારા સ્ટોરેજમાં વિગતો સંગ્રહ કરવામાં અક્ષમ છીએ.',
  txt_sync_with_server: 'ડેટા સમન્વયિત કરો',
  txt_based_on_reviews: '%s સમીક્ષાઓના આધારે.',
  txt_based_on_review: '%s સમીક્ષાના આધારે.',
  txt_user_details_not_available: 'વપરાશકર્તા વિગતો ઉપલબ્ધ નથી.',
  txt_data_not_available: 'કોઈ ડેટા ઉપલબ્ધ નથી.',
  txt_shishya_under_guidance: 'શિષ્ય તમારા માર્ગદર્શન હેઠળ નોંધાયેલા છે',
  txt_shishyas_under_guidance: 'શિષ્યો તમારા માર્ગદર્શન હેઠળ નોંધાયેલા છે',
  txt_yes: 'હા',
  txt_logout_msg: 'શશું તમે ખરેખર લોગ આઉટ કરવા માંગો છો? ',
  txt_copied_to_clipboard: 'ક્લિપબોર્ડ માં કોપી થઇ ગયું છે',
  txt_refer_message:
    '"અરે, અહીં એક ખૂબ જ શૈક્ષણિક એપ્લિકેશન છે જે તમારા માટે ઉપયોગી થશે. કૃપા કરીને તેને ઇન્સ્ટોલ કરો અને આ રેફરલ કોડનો ઉપયોગ કરો: "',
  txt_share_message:
    '"અરે ત્યાં, એક ખૂબ જ શૈક્ષણિક એપ્લિકેશન છે જે તમારા માટે ઉપયોગી થશે. કૃપા કરીને તેને ઇન્સ્ટોલ કરો."',
  txt_course_completed: 'કોર્સ પૂર્ણ.',
  txt_please_record_audio: 'ઓડિયો રેકોર્ડ કરો.',
  txt_please_record_video: 'કૃપા કરીને કોઈ વિડિઓ પસંદ કરો અથવા રેકોર્ડ કરો.',
  txt_revie_submitted: 'સમીક્ષા સબમિટ.',
  txt_this_content_is_updated: 'સામગ્રી સફળતાપૂર્વક અપડેટ થઈ.',
  default_notification_channel_id: 'bimapaathshala_channel',
  fcm_message: 'નવો સંદેશ',
  txt_search_guru: 'ગુરુને શોધો',
  txt_guru_list: 'ગુરુ સૂચિ',
  txt_guru_under_guidance: 'ગુરુ',
  txt_gurus_under_guidance: 'ગુરુઓ',
  txt_my_guru: 'મારા ગુરુ',
  txt_please_enter_mobile_number: 'કૃપા કરીને તમારો મોબાઇલ નંબર દાખલ કરો.',
  txt_please_enter_valid_mobile_number:
    'કૃપા કરી તમારો માન્ય મોબાઇલ નંબર દાખલ કરો.',
  txt_please_enter_firstname: 'કૃપા કરીને તમારું પ્રથમ નામ દાખલ કરો.',
  txt_please_enter_last_name: 'કૃપા કરીને તમારું છેલ્લું નામ દાખલ કરો.',
  txt_please_enter_adharcard_no: 'કૃપા કરીને આધારકાર્ડ નંબર દાખલ કરો.',
  txt_please_enter_valid_adharcard_no: 'કૃપા કરીને માન્ય આધારકાર્ડ નંબર.',
  txt_please_enter_email_address: 'કૃપા કરીને ઇમેઇલ સરનામું દાખલ કરો.',
  txt_please_enter_valid_email_address:
    'કૃપા કરીને માન્ય ઇમેઇલ સરનામું દાખલ કરો.',
  txt_please_enter_occupation: 'વ્યવસાય દાખલ કરો.',
  txt_please_enter_date_of_birth: 'કૃપા કરીને જન્મ તારીખ દાખલ કરો.',
  txt_please_enter_age: 'કૃપા કરીને તમારી ઉંમર દાખલ કરો.',
  txt_please_enter_marital_status: 'કૃપા કરીને તમારી વૈવાહિક સ્થિતિ દાખલ કરો.',
  txt_enter_otp: 'કૃપા કરીને ઓટીપી દાખલ કરો.',
  txt_enter_digit_otp: 'કૃપા કરીને ઓટીપી દાખલ કરો.',
  txt_resend: 'કોડ ફરીથી મોકલો',
  txt_choose_profile_pic: 'પ્રોફાઇલ ચિત્ર પસંદ કરો.',
  txt_choose_adhar_card: 'આધારકાર્ડ ફોટો પસંદ કરો',
  txt_till_: '%s સુધી',
  txt_no_internet_exam_msg:
    'પરીક્ષા આપવા માટે તમારી પાસે સક્રિય ઇન્ટરનેટ કનેક્શન હોવું આવશ્યક છે.',
  txt_please_enter_title: 'કૃપા કરીને શીર્ષક દાખલ કરો.',
  txt_please_enter_date_time: 'કૃપા કરીને તારીખ અને સમય દાખલ કરો.',
  txt_please_enter_amount: 'કૃપા કરીને રકમ દાખલ કરો.',
  txt_please_enter_category: 'કૃપા કરીને ખર્ચની કેટેગરી દાખલ કરો.',
  txt_choose_bill: 'કૃપા કરીને બિલ પસંદ કરો.',
  txt_please_enter_valid_adharcard: 'કૃપા કરીને આધાર કાર્ડ દાખલ કરો.',
  txt_no_viewer_to_view_file: 'આ ફાઇલને જોવા માટે કોઈ દર્શક નથી.',
  txt_unable_to_create_channel: 'ચેનલ બનાવવામાં અસમર્થ.',
  txt_shishya_list: 'શિષ્ય સૂચિ',
  no_notifications: 'કોઈ સૂચના ડેટા ઉપલબ્ધ નથી.',
  no_notifications_msg: 'કોઈ સૂચના ઉપલબ્ધ નથી.',
  no_upcoming_session: 'કોઈ આવનારું સત્ર નથી',
  no_completed_session: 'કોઈ પૂર્ણ સત્ર નથી.',
  no_certificate_message:
    'તમારી પાસે હજી પ્રમાણપત્રો નથી. કૃપા કરીને પ્રમાણપત્ર મેળવવા માટે કોઈ અભ્યાસક્રમ પૂર્ણ કરો.',
  no_expense_data: 'ખર્ચ ડેટા ઉપલબ્ધ નથી.',
  no_attendance_log: 'હાજરી લોગ ઉપલબ્ધ નથી.',
  txt_new_message: 'નવો સંદેશ',
  txt_welcome: 'સ્વાગત છે',
  txt_data_not_available_leaderboard:
    'તમે લીડરબોર્ડ પર પ્રથમ હોઈ શકશો, ઉતાવળ કરો અને હમણાં અમારા આકારણીઓ પસાર કરો!',
  txt_please_wait_for_internet_to_upload_bill:
    'જ્યારે તમે ઑફ્લાઈન હોવ ત્યારે તમે બિલ અપલોડ કરી શકતા નથી. પછીથી ફરી પ્રયાસ કરો.',
  txt_ok: 'બરાબર',
  txt_time_over_message: 'સમય સમાપ્ત થયો છે. સારો પ્રયાસ.',
  txt_record: 'રેકોર્ડ',
  txt_stop_record: 'રેકોર્ડિંગ બંધ કરો',
  txt_play: 'રમો',
  txt_stop: 'રોકો',
  txt_review_submitted: 'સમીક્ષા સબમિટ.',
  txt_view_courses: 'અભ્યાસક્રમો જુઓ',
  txt_choose_country: 'દેશ પસંદ કરો',
  txt_india: 'ભારત',
  txt_south_africa: 'દક્ષિણ આફ્રિકા',
  txt_sri_lanka: 'શ્રીલંકા',
  txt_bangladesh: 'બાંગ્લાદેશ',
  txt_indonesia: 'ઇન્ડોનેશિયા',
  txt_session_detail_updated: 'સત્ર વિગતો સફળતાપૂર્વક અપડેટ થઈ.',
  txt_session_download_success: 'સત્ર વિગતો સફળતાપૂર્વક ડાઉનલોડ થઈ.',
  txt_article_updated: 'લેખ વિગતો સફળતાપૂર્વક અપડેટ થઈ.',
  txt_article_download: 'લેખ વિગતો સફળતાપૂર્વક ડાઉનલોડ થઈ.',
  txt_video_updated: 'વિડિઓ વિગતો સફળતાપૂર્વક અપડેટ થઈ.',
  txt_video_download: 'વિડિઓ વિગતો સફળતાપૂર્વક ડાઉનલોડ થઈ.',
  txt_course_updated: 'કોર્સ વિગતો સફળતાપૂર્વક અપડેટ થયા.',
  txt_course_download: 'કોર્સ વિગતો સફળતાપૂર્વક ડાઉનલોડ થઈ.',
  txt_no_expense_data_available_to_export: 'નિકાસ કરવા માટે કોઈ ખર્ચ ડેટા નથી.',
  txt_no_attendance_to_export: 'નિકાસ કરવા માટે કોઈ હાજરી ડેટા નથી.',
  txt_sync_started_with_server: 'સમન્વયન સર્વરથી પ્રારંભ થયું.',
  txt_recording: 'રેકોર્ડિંગ વગાડવું.',
  txt_recording_stopped: 'રેકોર્ડિંગ બંધ થયું.',
  txt_recording_started: 'રેકોર્ડિંગ પ્રારંભ થયું.',
  txt_please_complete_section:
    'કૃપા કરીને આગળનાને અનલૉક કરવા માટે વિભાગ પૂર્ણ કરો.',
  txt_pending_assessment: 'બાકી આકારણી',
  txt_otp_retry_failed: 'OTP મોકલવાનું નિષ્ફળ થયું.',
  txt_otp_retry_success: 'OTP સફળતાપૂર્વક મોકલ્યો.',
  txt_invalid_otp: 'કૃપા કરીને માન્ય ઓટીપી દાખલ કરો.',
  txt_unable_to_send_review: 'સમીક્ષા સબમિટ કરવામાં અસમર્થ.',
  txt_unable_to_submit_quiz: 'ક્વિઝ સબમિટ કરવામાં અસમર્થ.',
  txt_no_assessment: 'અમે આકારણી વિગતો લાવવામાં અસમર્થ છીએ.',
  txt_no_data_available: 'કોઈ ડેટા ઉપલબ્ધ નથી.',
  txt_unable_to_register:
    'માફ કરશો અમે તમારા એકાઉન્ટની નોંધણી કરવામાં અસમર્થ છીએ.',
  txt_unable_to_update_account:
    'માફ કરશો, અમે તમારી વિગતો અપડેટ કરવામાં અસમર્થ છીએ.',
  txt_shishyas_course_watch_counter: '%s શિષ્યોએ આ કોર્સ જોયો છે.',
  txt_shishya_course_watch_counter: '%s શિષ્યે આ કોર્સ જોયો છે.',
  txt_shishya_are_attending_session: '%s શિષ્ય સત્રમાં ભાગ લઈ રહ્યા છે.',
  txt_shishyas_are_attending_session: '%s શિષ્ય સત્રમાં ભાગ લઈ રહ્યા છે.',
  txt_profile_updated: 'પ્રોફાઇલ સફળતાપૂર્વક અપડેટ થઈ.',
  txt_data_not_available_session: 'સત્ર ડેટા ઉપલબ્ધ નથી',
  no_article_message: 'કોઈ લેખ ઉપલબ્ધ નથી.',
  no_course_message: 'કોઈ કોર્સ ઉપલબ્ધ છે.',
  no_video_message: 'કોઈ વિડિઓ ઉપલબ્ધ નથી',
  txt_session_end_successfully: 'સત્ર સફળતાપૂર્વક સમાપ્ત થયું.',
  txt_session_end_failed: 'સત્ર સમાપ્ત કરવામાં અસમર્થ.',
  txt_to_be_launched_soon: 'ટૂંક સમયમાં શરૂ કરવામાં આવશે',
  txt_you_can_not_start_day_again: 'તમે ફરીથી "પ્રારંભ દિવસ" કરી શકતા નથી.',
  txt_view_more: 'વધુ જુઓ',
  txt_view_less: 'ઓછા જુઓ',
  txt_difficult_to_understand: 'સમજવું મુશ્કેલ.',
  txt_too_fast: 'ખૂબ ઝડપી.',
  txt_other: 'અન્ય',
  txt_shishya_already_added_session:
    'આ શિષ્ય સત્રમાં પહેલાથી જ ઉમેરવામાં આવ્યું છે.',
  txt_no_match_found: 'કોઈ મેચ મળી નથી.',
  txt_expenses_added_success: 'ખર્ચ સફળતાપૂર્વક ઉમેર્યો.',
  txt_expenses_added_failed: 'ખર્ચ ઉમેરવામાં અસમર્થ.',
  txt_shishya_already_added: 'શિષ્ય્યા પહેલાથી જ ઉમેરવામાં આવી છે.',
  txt_shishya_have_attend_session: 'શિષ્યે આ સત્રમાં ભાગ લીધો છે',
  txt_shishyas_have_attend_session: 'શિષ્યોએ આ સત્રમાં ભાગ લીધો છે',
  txt_can_not_start_session_zero_shishya:
    'આ સત્રમાં કોઈ શિષ્ય ઉમેર્યું નથી તેથી તમે સત્ર શરૂ કરી શકતા નથી.',
  txt_pending_assessment_message:
    'કૃપા કરીને આગલા %s ને અનલોક કરવા માટે %s જુઓ.',
  txt_it_seems_sanchalak:
    'એવું લાગે છે કે તમારી વિગતો સંચાલક તરીકે નોંધાયેલ છે. કૃપા કરીને એડમિનનો સંપર્ક કરો.',
  no_attended_session: 'હાજર સત્ર નથી',
  txt_add_more_details: 'વધુ વિગતો ઉમેરો',
  txt_please_enter_valid_pincode: 'કૃપા કરી માન્ય પિનકોડ દાખલ કરો.',
  txt_please_enter_pincode: 'કૃપા કરીને પિનકોડ દાખલ કરો',
  txt_can_not_start_session_before_date:
    'તમે સત્રની તારીખ પહેલાં સત્ર શરૂ કરી શકતા નથી.',
  txt_video_not_available: 'વિડિઓ ઉપલબ્ધ નથી.',
  txt_audio_not_available: 'ઓડિયો ઉપલબ્ધ નથી.',
  txt_file_not_available: 'ફાઇલ ઉપલબ્ધ નથી.',
  font_size: ['નાનું', 'માધ્યમ', 'મોટું', 'વધારાનો મોટો'],
  occupation: [
    'ખેડૂત',
    'એકાઉન્ટન્ટ',
    'ડ્રાઈવર',
    'ક્લીનર',
    'બાંધકામ મજૂરી',
    'વિદ્યાર્થી',
    'માછીમાર',
    'નર્સ',
    'ઓફિસ નો કારકુન',
    'સેલ્સપર્સન',
    'સીવણ મશીન ઓપરેટર',
    'દુકાનદાર',
    'દરજી',
    'શિક્ષક',
    'શાકભાજી લણણી કરનાર',
    'શાકભાજી પીકર',
    'વેઈટર',
    'અન્ય',
  ],
  dependent: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
  maritalstatus: ['પરણિત', 'અપરિણીત'],
  mothertonge: ['હિન્દી', 'અંગ્રેજી', 'ગુજરાતી', 'મરાઠી', 'અન્ય'],
  expense_category: ['મુસાફરી', 'ખોરાક', 'અન્ય'],
};
