export const HIN = {
  app_name: ' बिमा पाठशाला ',
  txt_submit: ' जमा करें ',
  txt_education_made_easy: ' शिक्षा को आसान बनाया ',
  txt_company_name_copy: ' कंपनी का नाम। सभी अधिकार सुरक्षित। ',
  txt_select_role: ' भूमिका का चयन करें ',
  txt_guru: ' गुरु ',
  txt_shishya: ' शिष्य ',
  txt_login: ' लॉगिन करें',
  txt_register: ' रजिस्टर करें ',
  txt_access_your_account: 'अपने खाते पर पहुंचे ',
  txt_start_learning_marketing: 'वित्त कोर्स सीखना शुरू करें',
  txt_phone_number_comp: ' फ़ोन नंबर * ',
  txt_password_comp: ' पासवर्ड * ',
  txt_dont_have_account: 'खाता नहीं है? ',
  txt_create_account: ' खाता बनाएँ ',
  txt_firstname_comp: ' पहला नाम * ',
  txt_lastname_comp: ' सरनेम * ',
  txt_email_address_comp: ' ईमेल पता ',
  txt_proceed: ' आगे बढ़ें ',
  txt_already_have_account: ' पहले से ही एक खाता है? ',
  txt_authentication_code: ' प्रमाणीकरण कोड ',
  txt_verifying_mobile_number: ' अपना मोबाइल नंबर सत्यापित करना ',
  txt_resend_code: '%s मिनट में कोड भेजें ',
  txt_continue_registeration: ' पंजीकरण जारी रखें ',
  txt_pending_details: ' लंबित विवरण ',
  txt_gender: ' लिंग ',
  txt_male: ' पुरुष ',
  txt_female: ' महिला ',
  txt_occupation_comp: ' व्यवसाय ',
  txt_date_of_birth_comp: ' जन्म तिथि ',
  txt_age_comp: ' आयु ',
  txt_mother_tongue_comp: ' मातृभाषा ',
  txt_marital_status_comp: ' वैवाहिक स्थिति ',
  txt_dependent: ' आश्रित ',
  txt_address: ' पता ',
  txt_locality: ' स्थानीयता / डाकघर ',
  txt_city: ' शहर / जिला / क्षेत्र ',
  txt_pin_code: ' पिन कोड *',
  txt_state: ' राज्य ',
  txt_search_learning_content: ' पाठ्यक्रम खोजें ',
  txt_courses: ' पाठ्यक्रम ',
  txt_see_all: ' सभी देखें ',
  txt_videos: ' वीडियो ',
  txt_articles: ' लेख ',
  txt_home: ' होम ',
  txt_upcoming_sessions: ' आगामी सत्र ',
  txt_attended_sessions: ' संलग्न सत्र ',
  txt_certificates: ' प्रमाणपत्र ',
  txt_refer_friend: ' मित्र को आमंत्रित करें',
  txt_feedback: ' प्रतिपुष्टि ',
  txt_share: ' शेयर ',
  txt_logout: ' लॉगआउट ',
  txt_reviews: ' समीक्षाएं ',
  txt_review: ' समीक्षा ',
  txt_comments: ' टिप्पणियाँ ',
  txt_comment: ' टिप्पणी ',
  txt_sessions: ' सत्र ',
  txt_session: ' सत्र ',
  txt_detail: ' विवरण ',
  txt_curriculum: ' पाठ्यक्रम ',
  txt_start_session: ' सत्र प्रारंभ करें ',
  txt_end_session: ' सत्र समाप्त करें ',
  txt_search_shishya: 'शिष्य खोजें ',
  txt_add_new_shishya: ' नया शिष्य जोड़ें ',
  txt_add_shishya: ' शिष्य जोड़ें ',
  txt_cancel: ' रद्द करें ',
  txt_shishya_will_be_joining: ' शिष्य सत्र में शामिल होगा ',
  txt_brief: ' संक्षिप्त ',
  txt_quiz: ' प्रश्नोत्तरी ',
  txt_certificate: ' प्रमाणपत्र ',
  txt_add_new_comment: 'नई टिप्पणी जोड़ें ',
  txt_close: ' बंद करें ',
  txt_download_certificate: ' प्रमाणपत्र डाउनलोड करें ',
  txt_next_que: ' अगला प्रश्न ',
  txt_submit_answer: ' जवाब सबमिट करें ',
  txt_try_again: ' पुन: प्रयास करें, आप शायद इसे अगली बार प्राप्त कर लेंगे ',
  txt_another_attempt: ' एक और प्रयास करे ',
  txt_results: ' परिणाम ',
  txt_upcoming_session: ' आगामी सत्र ',
  txt_completed_session: ' पूर्ण सत्र ',
  txt_expense_manager: ' व्यय प्रबंधक ',
  txt_expenses: ' खर्च ',
  txt_documents: ' दस्तावेज़ ',
  txt_upcoming: ' आगामी ',
  txt_attended: ' संलग्न ',
  txt_submit_feedback: 'प्रतिपुष्टि दें ',
  txt_text: ' पाठ ',
  txt_audio: ' ऑडियो ',
  txt_video: ' वीडियो ',
  txt_my_profile: ' मेरा प्रोफ़ाइल ',
  txt_basic_info: ' बुनियादी जानकारी ',
  txt_more_info: ' अधिक जानकारी ',
  txt_update_info: 'जानकारी अपडेट करें ',
  txt_choose_language: ' Choose Language ',
  txt_english: ' अंग्रेजी ',
  txt_choose_role: ' भूमिका चुनें ',
  txt_adhar_card_no: ' आधार कार्ड नंबर * ',
  txt_referral_code: ' रेफरल कोड ',
  txt_pay_and_subscribe: '%s भुगतान करें और सदस्यता लें ',
  txt_next_question: ' अगला प्रश्न ',
  txt_yes_want_to_exit: ' हां, मैं बाहर निकलना चाहता हूं ',
  txt_congratulations: ' बधाई ',
  txt_succesfully_completed_course:
    'आपने पाठ्यक्रम के इस %s खंड को सफलतापूर्वक पूरा कर लिया है। ',
  txt_write_your_feedback_here: ' कृपया अपनी प्रतिक्रिया यहाँ साझा करें। ',
  txt_search_expense: ' खोज व्यय ',
  txt_export: 'निर्यात',
  txt_add_new_expense: ' नया व्यय जोड़ें ',
  txt_expense_will_be_verified: ' खर्च का सत्यापन किया जाएगा.',
  txt_expense_title_com: ' व्यय शीर्षक * ',
  txt_date_time_com: ' दिनांक और समय * ',
  txt_amount_com: ' रकम * ',
  txt_expense_category_com: ' व्यय श्रेणी ',
  txt_add_expense: ' व्यय जोड़ें ',
  txt_pending: ' लंबित ',
  txt_verified_shishya: ' सत्यापित शिष्य ',
  txt_upload: ' अपलोड ',
  txt_adhar_card: ' आधार कार्ड ',
  txt_start_day: ' प्रारंभ दिवस ',
  txt_end_day: ' समाप्ति दिवस ',
  txt_chat_with_guru: ' गुरु के साथ बातचीत करें ',
  txt_guru_shishya_chat: ' गुरु और शिष्य बातचीत ',
  txt_my_attendance_log: ' मेरी उपस्थिति लॉग ',
  txt_refer_a_friend: 'मित्र को आमंत्रित करें ',
  txt_font_size_settings: ' फ़़ॉन्ट आकार सेटिंग्स ',
  txt_leaderboard: ' लीडर बोर्ड ',
  txt_account: ' खाता ',
  txt_got_it: ' मिल गया ',
  txt_verification_status: ' सत्यापन स्थिति ',
  txt_upload_bill: ' अपलोड बिल ',
  navigation_drawer_open: 'नेविगेशन दराज खोलें ',
  navigation_drawer_close: 'नेविगेशन दराज बंद करें ',
  txt_view: ' देखना ',
  txt_download: 'डाउनलोड ',
  txt_notification: 'अधिसूचना ',
  txt_help: ' मदद ',
  txt_queries_response: ' प्रश्नों और प्रतिक्रियाएँ ',
  txt_course_details: ' कोर्स विवरण ',
  txt_start: ' प्रारंभ ',
  txt_my_shishya: 'मेरा शिष्य ',
  txt_approved: ' स्वीकृत ',
  txt_sent_back: ' भेजा गया वापस ',
  txt_completed: ' पूर्ण ',
  txt_session_detail: ' सत्र विवरण ',
  txt_take_attendance: ' अटेंडेंस लें ',
  txt_feedback_desc:
    'हमें यह जानकर अच्छा लगेगा कि आप हमारे बारे में क्या सोचते हैं। कृपया हमें लिखें और अपनी प्रतिक्रिया साझा करें।',
  txt_refer: 'उल्लेख ',
  txt_copy: ' कॉपी करें ',
  txt_settings: 'समायोजन ',
  txt_select_district_wise: ' जिला वार का चयन करें ',
  txt_search_queries: 'प्रश्नों की खोज करें ',
  txt_search_sessions: 'सत्रों की खोज करें ',
  txt_search_by_date: ' दिनांक द्वारा खोजें ',
  txt_shishy_list: 'शिष्य सूची ',
  txt_expenses_total: ' खर्च कुल ',
  txt_sent_back_expenses: ' वापस भेजे गए व्यय ',
  txt_sent_back_expenses_total: ' वापस भेजे गए कुल खर्च ',
  txt_pending_expenses: ' लंबित व्यय ',
  txt_pending_expenses_total: ' लंबित व्यय कुल ',
  txt_some_thing_wrong:
    ' उफ़! कुछ गड़बड़ हो गई। कृपया बाद में पुनः प्रयास करें। ',
  txt_unable_to_connect:
    ' क्षमा करें, हम सर्वर से जुड़ने में असमर्थ हैं। कृपया बाद में पुनः प्रयास करें। ',
  txt_type_your_message_here: ' यहां अपना संदेश लिखें ... ',
  txt_contact_support: 'सहयोग टीम से संपर्क करें ',
  txt_go_back: ' वापस जाएं ',
  txt_account_deactivated: ' खाता निष्क्रिय किया गया ',
  txt_can_not_attempt_login:
    ' लॉगिन का प्रयास नहीं कर सकते। कृपया सहयोग टीम से संपर्क करें। ',
  txt_failed_course_message:
    'दुर्भाग्य से, आप पाठ्यक्रम का मूल्यांकन पूरा करने में विफल रहे हैं। हम आपसे प्रमाणपत्र प्राप्त करने के लिए पुनः प्रयास करने का आग्रह करते हैं।',
  txt_next_section: ' नेक्स्ट सेक्शन पर जाएँ ',
  txt_rate_exp: ' अपना अनुभव दर्ज करें ',
  txt_skip: ' छोड़ें ',
  txt_result_congratulations: ' बधाई! ',
  txt_sample_text: ' नमूना पाठ ',
  txt_sample_text_desc: ' तेज भूरे लोमड़ी आलसी कुत्ते के ऊपर कूदती है। ',
  txt_no_internet_connection: ' कृपया आप इंटरनेट कनेक्शन की जांच करें। ',
  txt_please_wait: ' कृपया प्रतीक्षा करें ... ',
  txt_save_settings: ' सेटिंग सहेजें ',
  txt_hindi: ' हिन्दी ',
  txt_marathi: ' मराठी ',
  txt_tamil: ' தமிழ் ',
  txt_save_font_settings: ' फ़ॉन्ट का आकार सहेजें ',
  txt_setting_saved: ' सेटिंग्स सफलतापूर्वक सहेजी गईं। ',
  txt_ratings: ' रेटिंग ',
  txt_please_fill_all_details: ' "कृपया सभी विवरण भरें।" ',
  txt_sections: ' अनुभाग ',
  txt_assessments: ' आकलन ',
  txt_section: ' सेक्शन ',
  txt_assessment: ' आकलन ',
  txt_courses_listed: ' सूचीबद्ध पाठ्यक्रम ',
  txt_articles_listed: ' सूचीबद्ध लेख ',
  txt_videos_listed: ' सूचीबद्ध वीडियो ',
  txt_course_listed: 'कोर्स सूचीबद्ध ',
  txt_article_listed: ' लेख सूचीबद्ध ',
  txt_video_listed: ' वीडियो सूचीबद्ध ',
  txt_user_details_not_found: 'उपयोगकर्ता विवरण नहीं मिला। कृपया लॉगिन करें। ',
  txt_sessions_listed: ' सत्र ',
  txt_session_listed: ' सत्र ',
  txt_shishya_going_to_attend_session:
    ' शिष्य इस सत्र में भाग लेने जा रहे हैं ',
  txt_shishyas_going_to_attend_session:
    ' शिष्य इस सत्र में भाग लेने जा रहे हैं ',
  txt_roll_no: ' "रोल नंबर:" ',
  txt_attendance_logged_msg:
    "आपकी उपस्थिति लॉग हो गई है। कृपया अपना दिन समाप्त होने के बाद \\'दिन खत्म\\' पर क्लिक करें।",
  txt_start_session_msg:
    "आपने सत्र शुरू कर दिया है। कृपया अपनी उपस्थिति बचाने के लिए \\'अंत सत्र\\' पर क्लिक करें",
  txt_please_grant_all_permission: ' कृपया अनुमति दें। ',
  txt_gujrati: ' ગુજરાતી ',
  txt_malyalam: ' മലയാളം ',
  txt_choose_language_converted: ' भाषा चुनें ',
  txt_language_settings: ' भाषा सेटिंग ',
  media_picker_select_from: 'से चुनें ',
  media_picker_camera: ' कैमरा ',
  media_picker_gallery: ' गैलरी ',
  media_picker_ok: 'ठीक है',
  media_picker_cancel: ' रद्द करें ',
  media_picker_some_permission_is_denied: ' कृपया अनुमति प्रदान करें। ',
  media_picker_you_need_to_grant_access_to:
    'आपको पहुंच प्रदान करने की आवश्यकता है ',
  media_picker_read_Write_external_storage: ' बाहरी संग्रहण पढ़ें और लिखें ',
  txt_choose_photo: ' फोटो चुनें ',
  txt_duration: ' "अवधि:" ',
  txt_guru_name: ' "गुरु का नाम:" ',
  txt_course_duration: ' "अवधि:" ',
  txt_choose: 'चुनें ',
  txt_from_gallery: ' गैलरी से ',
  txt_from_camera: ' कैमरा से ',
  txt_update_language: ' भाषा अपडेट करें ',
  txt_choose_language_convenience: ' कृपया अपनी पूर्वनिर्धारित भाषा चुनें। ',
  txt_minutes: ' मिनट ',
  txt_questions: 'प्रशन ',
  txt_question: 'प्रशन ',
  txt_please_give_answer: ' कृपया उत्तर चुनें ',
  txt_time_left: ' "समय जो बचा है" ',
  txt_time_up: 'समय समाप्त ',
  txt_mins: 'मिनट ',
  txt_quit_quiz:
    ' "यदि आपने परीक्षा छोड़ दी है, तो आप अगले अनुभाग का प्रयास करने के योग्य नहीं होंगे।"',
  title_activity_maps: ' नक्शा ',
  txt_downloading_certificate: ' प्रमाणपत्र डाउनलोड करना। ',
  txt_you_have_started_session:
    ' आपने सत्र शुरू कर दिया है, उपस्थिति बचाने के लिए समाप्त सत्र पर क्लिक करें ',
  txt_no_shishya_for_attendance: ' उपस्थिति के लिए कोई शिष्य चयनित नहीं। ',
  txt_no_shishya_available: ' कोई शिष्य उपलब्ध नहीं। ',
  txt_choose_video: ' वीडियो चुनें ',
  txt_chat: 'बातचीत',
  txt_curriculum_not_available: ' पाठ्यक्रम उपलब्ध नहीं है। ',
  txt_shishya_not_available: 'शिष्य उपलब्ध नहीं है। ',
  txt_rs: '"₹ "',
  error_message_url_not_valid: ' वीडियो यूआरएल मान्य नहीं है। ',
  txt_this_content_is_downloaded: ' यह पहले से डाउनलोड है। ',
  txt_unable_to_downloaded:
    ' क्षमा करें, हम इस फ़ाइल को डाउनलोड करने में असमर्थ हैं। बाद में पुन: प्रयास करें। ',
  txt_download_success: ' फ़ाइल सफलतापूर्वक डाउनलोड की गई ',
  txt_downloading_media: ' डाउनलोडिंग फाइलें। ',
  txt_approved_expenses: ' स्वीकृत व्यय ',
  txt_description: ' विवरण ',
  txt_date: ' दिनांक ',
  txt_amount: 'रकम ',
  txt_total_amount: ' "कुल रकम" ',
  txt_details_saved_on_local_storage: 'विवरण आपके संग्रहण में सहेजे गए हैं। ',
  txt_details_not_saved:
    ' क्षमा करें, हम आपके संग्रहण में विवरण सहेजने में असमर्थ हैं। ',
  txt_sync_with_server: ' सिंक डेटा ',
  txt_based_on_reviews: '%s समीक्षाओं के आधार पर। ',
  txt_based_on_review: '%s समीक्षा के आधार पर। ',
  txt_user_details_not_available: ' उपयोगकर्ता विवरण उपलब्ध नहीं हैं। ',
  txt_data_not_available: ' कोई डेटा उपलब्ध नहीं है। ',
  txt_shishya_under_guidance: ' शिष्य आपके मार्गदर्शन में नामांकित हैं ',
  txt_shishyas_under_guidance: ' आपके मार्गदर्शन के तहत शिष्य नामांकित हैं ',
  txt_yes: 'हाँ ',
  txt_logout_msg: ' क्या आप वाकई लॉगआउट करना चाहते हैं? ',
  txt_copied_to_clipboard: ' क्लिपबोर्ड पर कॉपी किया गया। ',
  txt_refer_message:
    '"अरे, यह एक अत्यंत शिक्षाप्रद एप्लिकेशनहै जो आपके लिए उपयोगी होगा। कृपया इसे स्थापित करें और इस रेफरल कोड का उपयोग करें"',
  txt_share_message:
    '"अरे, यह एक अत्यंत शिक्षाप्रद एप्लिकेशन है जो आपके लिए उपयोगी होगा। कृपया इसे स्थापित करें।"',
  txt_course_completed: ' कोर्स पूरा हुआ। ',
  txt_please_record_audio: ' कृपया ऑडियो रिकॉर्ड करें। ',
  txt_please_record_video: ' कृपया वीडियो चुनें या रिकॉर्ड करें। ',
  txt_revie_submitted: ' प्रस्तुत जमा करें। ',
  txt_this_content_is_updated: ' विवरण सफलतापूर्वक अपडेट की गई। ',
  default_notification_channel_id: 'bimapaathshala_channel ',
  fcm_message: ' नया संदेश ',
  txt_search_guru: ' गुरु खोजें ',
  txt_guru_list: ' गुरु सूची ',
  txt_guru_under_guidance: ' गुरु ',
  txt_gurus_under_guidance: ' गुरु ',
  txt_my_guru: ' मेरे गुरु ',
  txt_please_enter_mobile_number: ' कृपया अपना मोबाइल नंबर दर्ज करें। ',
  txt_please_enter_valid_mobile_number:
    ' कृपया अपना मान्य मोबाइल नंबर दर्ज करें। ',
  txt_please_enter_firstname: ' कृपया अपना पहला नाम दर्ज करें। ',
  txt_please_enter_last_name: ' कृपया अपना अंतिम नाम दर्ज करें। ',
  txt_please_enter_adharcard_no: ' कृपया आधार कार्ड नंबर दर्ज करें। ',
  txt_please_enter_valid_adharcard_no: 'कृपया मान्य आधार कार्ड नंबर दर्ज करें ',
  txt_please_enter_email_address: ' कृपया ईमेल पता दर्ज करें। ',
  txt_please_enter_valid_email_address: ' कृपया मान्य ईमेल पता दर्ज करें। ',
  txt_please_enter_occupation: ' कृपया व्यवसाय दर्ज करें। ',
  txt_please_enter_date_of_birth: ' कृपया जन्म तिथि दर्ज करें। ',
  txt_please_enter_age: ' अपनी आयु दर्ज करें। ',
  txt_please_enter_marital_status: ' कृपया अपनी वैवाहिक स्थिति दर्ज करें। ',
  txt_enter_otp: ' कृपया ओटीपी दर्ज करें। ',
  txt_enter_digit_otp: ' कृपया ओटीपी दर्ज करें। ',
  txt_resend: ' कोड पुनः भेजें ',
  txt_choose_profile_pic: ' एक प्रोफ़ाइल चित्र चुनें। ',
  txt_choose_adhar_card: ' आधार कार्ड फोटो चुनें ',
  txt_till_: '%s तक ',
  txt_no_internet_exam_msg:
    ' आपको परीक्षा देने के लिए एक सक्रिय इंटरनेट कनेक्शन की आवश्यकता होगी। ',
  txt_please_enter_title: ' कृपया शीर्षक दर्ज करें। ',
  txt_please_enter_date_time: ' कृपया दिनांक और समय दर्ज करें। ',
  txt_please_enter_amount: ' कृपयारकम दर्ज करें। ',
  txt_please_enter_category: ' कृपया व्यय श्रेणी दर्ज करें। ',
  txt_choose_bill: ' कृपया बिल चुनें। ',
  txt_please_enter_valid_adharcard: ' कृपया आधार कार्ड दर्ज करें। ',
  txt_no_viewer_to_view_file: ' इस फ़ाइल को देखने के लिए कोई दर्शक नहीं है। ',
  txt_unable_to_create_channel: ' चैनल बनाने में असमर्थ। ',
  txt_shishya_list: ' शिष्य सूची ',
  no_notifications: ' कोई सूचना डेटा उपलब्ध नहीं है। ',
  no_notifications_msg: ' कोई अधिसूचना उपलब्ध नहीं है। ',
  no_upcoming_session: ' कोई आगामी सत्र नहीं ',
  no_completed_session: ' कोई पूर्ण सत्र नहीं। ',
  no_certificate_message:
    'आपके पास अभी तक कोई प्रमाण पत्र नहीं है। प्रमाणपत्र प्राप्त करने के लिए कृपया एक कोर्स पूरा करें।',
  no_expense_data: ' व्यय डेटा उपलब्ध नहीं है। ',
  no_attendance_log: ' उपस्थिति लॉग उपलब्ध नहीं है। ',
  txt_new_message: ' नया संदेश  से',
  txt_welcome: ' स्वागत ',
  txt_data_not_available_leaderboard:
    ' आप लीडरबोर्ड पर पहले एक हो सकते हैं, जल्दी करो और अब हमारे आकलन पास करो! ',
  txt_please_wait_for_internet_to_upload_bill:
    ' आप ऑफ़लाइन होने पर बिल अपलोड नहीं कर सकते। बाद में पुन: प्रयास करें। ',
  txt_ok: 'ठीक है',
  txt_time_over_message: ' समय समाप्त हो गया है। अच्छी कोशिश। ',
  txt_record: ' रिकॉर्ड ',
  txt_stop_record: ' रिकॉर्डिंग रोकें ',
  txt_play: 'चलाएं ',
  txt_stop: 'रुकें ',
  txt_review_submitted: 'समीक्षा प्रस्तुत की गई। ',
  txt_view_courses: 'कोर्स देखें ',
  txt_choose_country: ' देश चुनें ',
  txt_india: ' भारत ',
  txt_south_africa: ' दक्षिण अफ्रीका ',
  txt_sri_lanka: ' श्रीलंका ',
  txt_bangladesh: ' बांग्लादेश ',
  txt_indonesia: ' इंडोनेशिया ',
  txt_session_detail_updated: ' सत्र विवरण सफलतापूर्वक अपडेट किया गया। ',
  txt_session_download_success: ' सत्र विवरण सफलतापूर्वक डाउनलोड किया गया। ',
  txt_article_updated: ' लेख विवरण सफलतापूर्वक अपडेट किया गया। ',
  txt_article_download: ' लेख विवरण सफलतापूर्वक डाउनलोड किया गया। ',
  txt_video_updated: ' वीडियो विवरण सफलतापूर्वक अपडेट किया गया। ',
  txt_video_download: ' वीडियो विवरण सफलतापूर्वक डाउनलोड किया गया। ',
  txt_course_updated: ' कोर्स विवरण सफलतापूर्वक अपडेट किया गया। ',
  txt_course_download: ' कोर्स विवरण सफलतापूर्वक डाउनलोड किया गया। ',
  txt_no_expense_data_available_to_export:
    ' निर्यात करने के लिए कोई डेटा नहीं है। ',
  txt_no_attendance_to_export: ' निर्यात के लिए कोई उपस्थिति डेटा नहीं है।',
  txt_sync_started_with_server: ' सर्वर के साथ सिंक शुरू किया। ',
  txt_recording: ' रिकॉर्डिंग बजाना। ',
  txt_recording_stopped: ' रिकॉर्डिंग बंद कर दी गई। ',
  txt_recording_started: ' रिकॉर्डिंग शुरू हुई। ',
  txt_please_complete_section:
    ' अगले एक को अनलॉक करने के लिए कृपया पूर्ण अनुभाग देखें। ',
  txt_pending_assessment: ' लंबित मूल्यांकन ',
  txt_otp_retry_failed: 'ओटीपी भेजने में विफल रहा। ',
  txt_otp_retry_success: 'ओटीपी सफलतापूर्वक भेजा गया। ',
  txt_invalid_otp: ' कृपया एक वैध ओटीपी दर्ज करें। ',
  txt_unable_to_send_review: ' समीक्षा सबमिट करने में असमर्थ। ',
  txt_unable_to_submit_quiz: ' प्रश्नोत्तरी सबमिट करने में असमर्थ। ',
  txt_no_assessment: ' हम मूल्यांकन विवरण लाने में असमर्थ हैं। ',
  txt_no_data_available: ' कोई डेटा उपलब्ध नहीं है। ',
  txt_unable_to_register:
    ' क्षमा करें हम आपका खाता रजिस्टर करने में असमर्थ हैं। ',
  txt_unable_to_update_account:
    ' क्षमा करें हम आपके विवरण को अपडेट करने में असमर्थ हैं। ',
  txt_shishyas_course_watch_counter: '%s शिष्य ने यह कोर्स देखा है। ',
  txt_shishya_course_watch_counter: '%s शिष्य ने इस कोर्स को छोड़ दिया है। ',
  txt_shishya_are_attending_session: '%s शिष्य सत्र में भाग ले रहे हैं। ',
  txt_shishyas_are_attending_session: '%s शिष्य सत्र में भाग ले रहा है। ',
  txt_profile_updated: ' प्रोफ़ाइल सफलतापूर्वक अपडेट की गई। ',
  txt_data_not_available_session: ' सत्र डेटा उपलब्ध नहीं है ',
  no_article_message: ' कोई लेख उपलब्ध नहीं है। ',
  no_course_message: ' कोई कोर्स उपलब्ध नहीं। ',
  no_video_message: ' कोई वीडियो उपलब्ध नहीं ',
  txt_session_end_successfully: ' सत्र सफलतापूर्वक समाप्त हो गया। ',
  txt_session_end_failed: ' सत्र समाप्त करने में असमर्थ। ',
  txt_to_be_launched_soon: ' जल्द ही शुरू किया जाएगा ',
  txt_you_can_not_start_day_again: 'आप फिर से दिन शुरू नहीं कर सकते। ',
  txt_view_more: ' और देखें ',
  txt_view_less: ' कम देखें ',
  txt_difficult_to_understand: 'समझना मुश्किल।',
  txt_too_fast: 'बहुत तेज।',
  txt_other: 'अन्य',
  txt_shishya_already_added_session: 'शिश्या को पहले ही सत्र में जोड़ा जाता है',
  txt_no_match_found: 'कोई मेल नहीं मिला।',
  txt_expenses_added_success: 'व्यय सफलतापूर्वक जोड़ा गया।',
  txt_expenses_added_failed: 'व्यय जोड़ने में असमर्थ।',
  txt_shishya_already_added: 'शिश्या पहले से ही जोड़ा जाता है।',
  txt_shishya_have_attend_session: 'इस सत्र में शिश्या ने भाग लिया है',
  txt_shishyas_have_attend_session: 'इस सत्र में शिश्या ने भाग लिया है',
  txt_can_not_start_session_zero_shishya:
    'इस सत्र में कोई शिश्या नहीं जोड़ा गया है जिससे आप सत्र शुरू नहीं कर सकते।',
  txt_pending_assessment_message:
    'कृपया अगले %s को अनलॉक करने के लिए %s देखें।',
  txt_it_seems_sanchalak:
    'ऐसा लगता है कि आपका विवरण संचलक के रूप में पंजीकृत है। कृपया व्यवस्थापक से संपर्क करें।',
  no_attended_session: 'सत्र में भाग नहीं लिया।',
  txt_add_more_details: 'अधिक विवरण जोड़ें',
  txt_please_enter_valid_pincode: 'कृपया मान्य पिनकोड दर्ज करें।',
  txt_please_enter_pincode: 'कृपया पिनकोड दर्ज करें।',
  txt_can_not_start_session_before_date:
    'आप सत्र की तारीख से पहले सत्र शुरू नहीं कर सकते।',
  txt_video_not_available: 'वीडियो उपलब्ध नहीं',
  txt_audio_not_available: 'ऑडियो उपलब्ध नहीं है।',
  txt_file_not_available: 'फाइल उपलब्ध नहीं है।',
  font_size: [' छोटे ', ' मध्यम ', ' बड़ा ', ' अतिरिक्त बड़ा '],
  occupation: [
    ' किसान ',
    ' लेखाकार ',
    ' चालक ',
    ' क्लीनर ',
    ' निर्माण श्रम ',
    ' छात्र ',
    ' मछुआरे ',
    ' नर्स ',
    ' कार्यालय क्लर्क ',
    ' विक्रेता ',
    ' सिलाई मशीन ऑपरेटर ',
    ' दुकानदार ',
    ' दर्जी ',
    ' शिक्षक ',
    ' वनस्पति हारवेस्टर ',
    ' सब्जी पिकर ',
    ' वेटर ',
    ' अन्य ',
  ],
  dependent: [
    '0 ',
    ' 1 ',
    ' 2 ',
    ' 3 ',
    ' 4 ',
    ' 5',
    ' 6 ',
    ' 7 ',
    ' 8 ',
    ' 9 ',
    ' 10 ',
  ],
  maritalstatus: [' विवाहित ', ' अविवाहित '],
  mothertonge: [' हिन्दी ', ' अंग्रेज़ी ', ' गुजराती ', ' मराठी ', ' दूसरों '],
  expense_category: [' सफर ', ' खाद्य ', ' दूसरों '],
};
