export const MHA = {
  app_name: ' बिमा पाठशाला ',
  txt_submit: ' सादर करा ',
  txt_education_made_easy: ' शिक्षण केली सोपे ',
  txt_company_name_copy: ' कंपनीचे नाव  सर्व हक्क राखीव ',
  txt_select_role: ' भूमिका ',
  txt_guru: ' गुरू ',
  txt_shishya: ' शिष्य ',
  txt_login: ' लॉगिन ',
  txt_register: ' नोंदणी करा ',
  txt_access_your_account: ' आपल्या खात्यात प्रवेश करा ',
  txt_start_learning_marketing: ' वित्त कोर्सेस शिकणे प्रारंभ करा ',
  txt_phone_number_comp: ' फोन नंबर * ',
  txt_password_comp: ' संकेतशब्द * ',
  txt_dont_have_account: ' अद्याप खाते नाही? ',
  txt_create_account: ' खाते तयार करा ',
  txt_firstname_comp: ' पहिले नाव * ',
  txt_lastname_comp: ' आडनाव * ',
  txt_email_address_comp: ' ईमेल पत्ता ',
  txt_proceed: ' पुढे जा ',
  txt_already_have_account: ' आधीपासूनच एक खाते आहे ',
  txt_authentication_code: ' प्रमाणीकरण कोड ',
  txt_verifying_mobile_number: ' आपला मोबाइल नंबर सत्यापित करणे ',
  txt_resend_code: ' कोड पुन्हा पाठवा %s मिनिट ',
  txt_continue_registeration: ' नोंदणी सुरू ठेवा ',
  txt_pending_details: ' प्रलंबित तपशील ',
  txt_gender: ' लिंग ',
  txt_male: ' पुरुष ',
  txt_female: ' महिला ',
  txt_occupation_comp: ' व्यवसाय ',
  txt_date_of_birth_comp: 'जन्म तारीख ',
  txt_age_comp: ' वय ',
  txt_mother_tongue_comp: ' मातृभाषा ',
  txt_marital_status_comp: ' वैवाहिक स्थिती ',
  txt_dependent: ' अवलंबित ',
  txt_address: ' पत्ता ',
  txt_locality: ' परिसर / पोस्ट ऑफिस ',
  txt_city: ' शहर / जिल्हा / प्रदेश ',
  txt_pin_code: ' पिन कोड *',
  txt_state: ' राज्य ',
  txt_search_learning_content: ' शोध अभ्यासक्रम ',
  txt_courses: ' अभ्यासक्रम ',
  txt_see_all: ' सर्व ',
  txt_videos: ' व्हिडिओ ',
  txt_articles: ' लेख ',
  txt_home: ' मुख्यपृष्ठ ',
  txt_upcoming_sessions: ' आगामी सत्रे ',
  txt_attended_sessions: ' सत्रे उपस्थित ',
  txt_certificates: ' प्रमाणपत्रे ',
  txt_refer_friend: ' मित्रालासूचव ',
  txt_feedback: ' अभिप्राय ',
  txt_share: ' सामायिक करा ',
  txt_logout: ' लॉगआउट ',
  txt_reviews: ' पुनरावलोकने ',
  txt_review: ' पुनरावलोकन ',
  txt_comments: ' टिप्पण्या ',
  txt_comment: ' टिप्पणी ',
  txt_sessions: ' सत्रे ',
  txt_session: ' सत्र ',
  txt_detail: ' तपशील ',
  txt_curriculum: ' अभ्यासक्रम ',
  txt_start_session: ' सत्र प्रारंभ करा ',
  txt_end_session: ' सत्र समाप्त करा ',
  txt_search_shishya: ' शोध शिष्य ',
  txt_add_new_shishya: ' नवीन शिष्य जोडा ',
  txt_add_shishya: ' शिष्य जोडा  ',
  txt_cancel: ' रद्द करा ',
  txt_shishya_will_be_joining: ' शिष्य सामील होईल ',
  txt_brief: ' संक्षिप्त ',
  txt_quiz: ' प्रश्नोत्तरी ',
  txt_certificate: ' प्रमाणपत्र ',
  txt_add_new_comment: ' नवीन टिप्पणी जोडा ',
  txt_close: ' बंद करा ',
  txt_download_certificate: ' प्रमाणपत्र डाउनलोड करा  ',
  txt_next_que: ' पुढील प्रश्न ',
  txt_submit_answer: ' उत्तरे सबमिट करा ',
  txt_try_again: ' पुन्हा प्रयत्न करा तुम्हाला कदाचित पुढच्या वेळी मिळेल ',
  txt_another_attempt: ' आणखी एक प्रयत्न ',
  txt_results: ' परिणाम ',
  txt_upcoming_session: ' आगामी सत्रे ',
  txt_completed_session: ' पूर्ण सत्रे ',
  txt_expense_manager: ' खर्च व्यवस्थापक ',
  txt_expenses: ' खर्च ',
  txt_documents: ' दस्तऐवज ',
  txt_upcoming: ' आगामी ',
  txt_attended: ' उपस्थित ',
  txt_submit_feedback: ' अभिप्राय सामायिक करा ',
  txt_text: ' मजकूर ',
  txt_audio: ' ऑडिओ ',
  txt_video: ' व्हिडिओ ',
  txt_my_profile: ' माझे प्रोफाइल ',
  txt_basic_info: ' मूलभूत माहिती ',
  txt_more_info: ' अधिक माहिती ',
  txt_update_info: ' माहिती अद्यतनित करा ',
  txt_choose_language: ' Choose Language ',
  txt_english: ' इंग्रजी ',
  txt_choose_role: ' भूमिका निवडा ',
  txt_adhar_card_no: ' आधार कार्ड क्रमांक * ',
  txt_referral_code: ' संदर्भ कोड ',
  txt_pay_and_subscribe: ' पैसे द्या आणि सदस्यता घ्या %s  ',
  txt_next_question: ' पुढील प्रश्न ',
  txt_yes_want_to_exit: ' होय, मी इच्छित करण्यासाठी बाहेर पडा ',
  txt_congratulations: ' अभिनंदन ! ',
  txt_succesfully_completed_course:
    ' पण आहे यशस्वीरित्या पूर्ण या विभागात च्या अर्थातच %s. ',
  txt_write_your_feedback_here: ' कृपया आपला अभिप्राय येथे सामायिक करा . ',
  txt_search_expense: ' शोध खर्च ',
  txt_export: ' निर्यात ',
  txt_add_new_expense: ' नवीन खर्च जोडा ',
  txt_expense_will_be_verified: ' जोडलेला खर्च अद्याप सत्यापित केलेला नाही . ',
  txt_expense_title_com: ' खर्चाचे शीर्षक * ',
  txt_date_time_com: ' तारीख आणि वेळ * ',
  txt_amount_com: ' रक्कम * ',
  txt_expense_category_com: ' खर्च वर्ग ',
  txt_add_expense: ' खर्च जोडा ',
  txt_pending: ' प्रलंबित ',
  txt_verified_shishya: ' सत्यापित शिष्य ',
  txt_upload: ' अपलोड ',
  txt_adhar_card: ' आधार कार्ड ',
  txt_start_day: ' प्रारंभ दिवस ',
  txt_end_day: ' समाप्ती दिवस ',
  txt_chat_with_guru: ' गुरूशी गप्पा मारा ',
  txt_guru_shishya_chat: ' गुरु आणि शिष्य गप्पा ',
  txt_my_attendance_log: ' माझा उपस्थिती लॉग ',
  txt_refer_a_friend: 'मित्रालासूचव ',
  txt_font_size_settings: ' फॉन्ट सेटिंग्ज ',
  txt_leaderboard: ' लीडर बोर्ड ',
  txt_account: ' खाते ',
  txt_got_it: ' समजले ',
  txt_verification_status: ' सत्यापन स्थिती ',
  txt_upload_bill: ' बिल अपलोड करा ',
  navigation_drawer_open: 'उघडा ',
  navigation_drawer_close: 'बंद करा ',
  txt_view: ' पहा ',
  txt_download: ' डाउनलोड करा ',
  txt_notification: ' सूचना ',
  txt_help: ' मदत ',
  txt_queries_response: ' शंका आणि प्रतिसाद ',
  txt_course_details: ' कोर्स तपशील ',
  txt_start: ' प्रारंभ करा ',
  txt_my_shishya: ' माझे शिष्य ',
  txt_approved: ' मंजूर ',
  txt_sent_back: ' परत पाठवलं ',
  txt_completed: ' पूर्ण ',
  txt_session_detail: ' सत्राचा तपशील ',
  txt_take_attendance: ' उपस्थिती घ्या ',
  txt_feedback_desc:
    ' आपण आमच्याबद्दल काय विचार करता हे आम्हाला जाणून घेण्यास आवडेल. कृपया आम्हाला लिहा आणि आपला अभिप्राय सामायिक करा . ',
  txt_refer: 'पहा  ',
  txt_copy: ' कॉपी ',
  txt_settings: ' सेटिंग्ज ',
  txt_select_district_wise: ' जिल्हा वार निवडा ',
  txt_search_queries: ' शोध क्वेरी ',
  txt_search_sessions: ' शोध सत्रे ',
  txt_search_by_date: ' तारखेनुसार शोध ',
  txt_shishy_list: ' शिष्य सूची ',
  txt_expenses_total: ' खर्च एकूण ',
  txt_sent_back_expenses: 'परत खर्च पाठविला ',
  txt_sent_back_expenses_total: ' एकूण खर्च परत पाठविला ',
  txt_pending_expenses: ' प्रलंबित खर्च ',
  txt_pending_expenses_total: ' प्रलंबित खर्च एकूण ',
  txt_some_thing_wrong:
    ' काहीतरी चुकीचे घडले आहे, कृपया थोड्यावेळाने प्रयत्न करा . ',
  txt_unable_to_connect:
    ' क्षमस्व आम्ही सर्व्हरशी कनेक्ट करण्यात अक्षम आहोत. पुन्हा प्रयत्न करा . ',
  txt_type_your_message_here: ' आपला संदेश येथे टाइप करा ... ',
  txt_contact_support: ' संपर्क समर्थन ',
  txt_go_back: ' परत जा ',
  txt_account_deactivated: ' खाते निष्क्रिय ',
  txt_can_not_attempt_login:
    ' लॉगिन प्रयत्न करू शकत नाही. कृपया समर्थनाशी संपर्क साधा. ',
  txt_failed_course_message:
    ' आपण कोर्स असाइनमेंट पूर्ण करण्यात अयशस्वी झाला प्रमाणपत्र घेण्यासाठी पुन्हा प्रयत्न करा . ',
  txt_next_section: ' पुढील विभागात जा ',
  txt_rate_exp: ' आपला अनुभव ला रेट करा ',
  txt_skip: ' वगळा ',
  txt_result_congratulations: ' अभिनंदन ! ',
  txt_sample_text: ' नमुना मजकूर ',
  txt_sample_text_desc: ' जलद तपकिरी कोल्हा बदलानुसार प्रती आळशी कुत्रा . ',
  txt_no_internet_connection: 'इंटरनेट कनेक्शन नाही . ',
  txt_please_wait: ' कृपया प्रतीक्षा करा . ',
  txt_save_settings: ' सेव्ह सेटिंग्ज ',
  txt_hindi: ' हिंदी ',
  txt_marathi: ' मराठी ',
  txt_tamil: ' தமிழ் ',
  txt_save_font_settings: ' फॉन्ट आकार जतन करा ',
  txt_setting_saved: ' सेटिंग्ज यशस्वीरित्या जतन केल्या . ',
  txt_ratings: ' रेटिंग ',
  txt_please_fill_all_details: ' "कृपया सर्व तपशील भरा . " ',
  txt_sections: ' विभाग ',
  txt_assessments: ' आकलन ',
  txt_section: ' विभाग ',
  txt_assessment: ' मूल्यांकन ',
  txt_courses_listed: ' अभ्यासक्रम सूचीबद्ध ',
  txt_articles_listed: ' लेख सूचीबद्ध ',
  txt_videos_listed: ' व्हिडिओ सूचीबद्ध  ',
  txt_course_listed: ' कोर्स सूचीबद्ध ',
  txt_article_listed: ' लेख सूचीबद्ध ',
  txt_video_listed: ' व्हिडिओ सूचीबद्ध ',
  txt_user_details_not_found:
    ' वापरकर्ता तपशील आढळला नाही . कृपया लॉगिन करा . ',
  txt_sessions_listed: ' सत्रे ',
  txt_session_listed: ' सत्र ',
  txt_shishya_going_to_attend_session: 'शिष्य या अधिवेशनात सहभागी होणार आहेत ',
  txt_shishyas_going_to_attend_session: 'शिष्य या अधिवेशनात सहभागी होणार आहेत',
  txt_roll_no: ' "रोल नंबर : " ',
  txt_attendance_logged_msg:
    'तुमची उपस्थिती लॉग  झाली आहे. कृपया आपला दिवस संपल्यानंतर  एंड दिवशी क्लिक करा . ',
  txt_start_session_msg:
    ' आपण सत्र सुरू केले आहे. कृपया आपली उपस्थिती वाचवण्यासाठी एंड सेशनवर क्लिक करा ',
  txt_please_grant_all_permission: 'कृपया परवानगी द्या . ',
  txt_gujrati: 'ગુજરાતી ',
  txt_malyalam: ' മലയാളം ',
  txt_choose_language_converted: ' भाषा निवडा ',
  txt_language_settings: ' भाषा सेटिंग्ज ',
  media_picker_select_from: 'पासून निवडा ',
  media_picker_camera: ' कॅमेरा ',
  media_picker_gallery: ' गॅलरी ',
  media_picker_ok: ' ओके ',
  media_picker_cancel: ' रद्द करा ',
  media_picker_some_permission_is_denied: ' कृपया परवानगी द्या . ',
  media_picker_you_need_to_grant_access_to:
    'आपल्याला प्रवेश मंजूर करण्याची आवश्यकता आहे ',
  media_picker_read_Write_external_storage: ' बाह्य स्टोरेज वाचा आणि लिहा ',
  txt_choose_photo: ' फोटो  निवडा  ',
  txt_duration: ' " कालावधी : " ',
  txt_guru_name: ' "गुरूचे नाव : " ',
  txt_course_duration: ' " कालावधी : " ',
  txt_choose: 'निवडा ',
  txt_from_gallery: ' गॅलरी पासून ',
  txt_from_camera: ' कॅमेरा पासून ',
  txt_update_language: ' भाषा अद्यतनित करा ',
  txt_choose_language_convenience: 'कृपया आपली पसंतीची भाषा निवडा. ',
  txt_minutes: ' मिनिटे ',
  txt_questions: ' प्रश्न ',
  txt_question: ' प्रश्न ',
  txt_please_give_answer: ' कृपया उत्तर निवडा ',
  txt_time_left: ' "उर्वरित वेळ : " ',
  txt_time_up: ' टाइम अप ',
  txt_mins: ' मिनिटे ',
  txt_quit_quiz:
    ' "आपण परीक्षा सोडल्यास आपण पुढील विभागात प्रयत्न करण्यास पात्र नाही" ',
  title_activity_maps: ' नकाशा ',
  txt_downloading_certificate: ' प्रमाणपत्र डाउनलोड करीत आहे . ',
  txt_you_have_started_session:
    " आआपण सत्र प्रारंभ केले आहे, उपस्थिती वाचविण्यासाठी \\'एंड ससेशन\\' वर क्लिक करा ",
  txt_no_shishya_for_attendance: ' उपस्थितीसाठी शिष्यची निवड झाली नाही . ',
  txt_no_shishya_available: ' कोणत्याही शिष्य उपलब्ध नाही . ',
  txt_choose_video: ' व्हिडिओ निवडा ',
  txt_chat: ' गप्पा ',
  txt_curriculum_not_available: ' अभ्यासक्रम उपलब्ध नाही . ',
  txt_shishya_not_available: ' शिष्य उपलब्ध नाही . ',
  txt_rs: ' "₹ " ',
  error_message_url_not_valid: ' व्हिडिओ यूआरएल वैध नाही . ',
  txt_this_content_is_downloaded: 'हे आधीपासून डाउनलोड केलेले आहे . ',
  txt_unable_to_downloaded:
    'क्षमस्व, आम्ही ही फाईल डाउनलोड करण्यात अक्षम आहोत. कृपया पुन्हा प्रयत्न करा . ',
  txt_download_success: ' फाईल यशस्वीरित्या डाउनलोड झाली ! ',
  txt_downloading_media: ' फायली डाउनलोड करीत आहे . ',
  txt_approved_expenses: ' मंजूर खर्च ',
  txt_description: ' वर्णन ',
  txt_date: ' तारीख ',
  txt_amount: ' रक्कम ',
  txt_total_amount: ' "एकूण रक्कम " ',
  txt_details_saved_on_local_storage:
    'तपशील आपल्या स्टोरेजमध्ये जतन केले आहेत . ',
  txt_details_not_saved:
    ' क्षमस्व, आम्ही आपल्या संग्रहात तपशील जतन करण्यात अक्षम आहोत. ',
  txt_sync_with_server: ' डेटा समक्रमित करा ',
  txt_based_on_reviews: ' आधारित वर %s आढावा . ',
  txt_based_on_review: ' आधारित वर %s पुनरावलोकन . ',
  txt_user_details_not_available: ' वापरकर्ता तपशील आहेत नाही उपलब्ध . ',
  txt_data_not_available: ' कोणताही डेटा उपलब्ध नाही . ',
  txt_shishya_under_guidance: ' शिष्य आपल्या मार्गदर्शनाखाली नोंदणीकृत आहे',
  txt_shishyas_under_guidance: 'शिष्य आपल्या मार्गदर्शनाखाली नोंदणीकृत आहे ',
  txt_yes: ' होय ',
  txt_logout_msg: ' आपली खात्री आहे की आपण लॉगआउट करू इच्छिता ? ',
  txt_copied_to_clipboard: 'क्लिपबोर्डवर कॉपी केले. ',
  txt_refer_message:
    ' "अहो, येथे एक अत्यंत शैक्षणिक अ‍ॅप आहे जे आपल्यासाठी उपयुक्त ठरेल. कृपया ते स्थापित करा आणि हा रेफरल कोड वापरा: " ',
  txt_share_message:
    ' "अहो, येथे एक अत्यंत शैक्षणिक अ‍ॅप आहे जे आपल्यासाठी उपयुक्त ठरेल. कृपया ते स्थापित करा." ',
  txt_course_completed: ' अभ्यासक्रम पूर्ण . ',
  txt_please_record_audio: ' कृपया ऑडिओ रेकॉर्ड करा . ',
  txt_please_record_video: ' कृपया एखादा व्हिडिओ निवडा किंवा रेकॉर्ड करा . ',
  txt_revie_submitted: ' पुनरावलोकन सबमिट केले . ',
  txt_this_content_is_updated: ' सामग्री यशस्वीरित्या अद्यतनित केली . ',
  default_notification_channel_id: 'bimapaathshala_channel',
  fcm_message: ' नवीन संदेश ',
  txt_search_guru: ' शोध गुरू ',
  txt_guru_list: ' गुरु यादी ',
  txt_guru_under_guidance: ' गुरू ',
  txt_gurus_under_guidance: ' गुरु ',
  txt_my_guru: ' माझे गुरु ',
  txt_please_enter_mobile_number: ' कृपया आपला मोबाइल नंबर प्रविष्ट करा . ',
  txt_please_enter_valid_mobile_number:
    ' कृपया आपला वैध मोबाइल नंबर प्रविष्ट करा . ',
  txt_please_enter_firstname: ' कृपया प्रथम नाव प्रविष्ट करा . ',
  txt_please_enter_last_name: 'कृपया आडनाव प्रविष्ट करा . ',
  txt_please_enter_adharcard_no: ' कृपया आधार कार्ड क्रमांक प्रविष्ट करा . ',
  txt_please_enter_valid_adharcard_no:
    ' कृपया वैध आधार कार्ड क्रमांक प्रविष्ट करा . ',
  txt_please_enter_email_address: ' कृपया ईमेल पत्ता प्रविष्ट करा . ',
  txt_please_enter_valid_email_address: ' कृपया वैध ईमेल पत्ता प्रविष्ट करा . ',
  txt_please_enter_occupation: ' कृपया व्यवसाय प्रविष्ट करा . ',
  txt_please_enter_date_of_birth: 'कृपया जन्मतारीख प्रविष्ट करा . ',
  txt_please_enter_age: ' कृपया आपले वय प्रविष्ट करा . ',
  txt_please_enter_marital_status: ' कृपया आपली वैवाहिक स्थिती प्रविष्ट करा . ',
  txt_enter_otp: ' कृपया ओटीपी प्रविष्ट करा . ',
  txt_enter_digit_otp: ' कृपया ओटीपी प्रविष्ट करा . ',
  txt_resend: ' कोड पुन्हा पाठवा ',
  txt_choose_profile_pic: ' निवडा एक प्रोफाइल चित्र . ',
  txt_choose_adhar_card: ' निवडा एक आधार कार्ड फोटो ',
  txt_till_: ' पर्यंत %s ',
  txt_no_internet_exam_msg:
    'परीक्षा देण्यासाठी आपल्याकडे सक्रिय इंटरनेट कनेक्शन असणे आवश्यक आहे . ',
  txt_please_enter_title: ' कृपया शीर्षक प्रविष्ट करा . ',
  txt_please_enter_date_time: ' कृपया तारीख आणि वेळ प्रविष्ट करा . ',
  txt_please_enter_amount: ' कृपया रक्कम प्रविष्ट करा . ',
  txt_please_enter_category: ' कृपया खर्च श्रेणी प्रविष्ट करा . ',
  txt_choose_bill: ' कृपया बिल निवडा . ',
  txt_please_enter_valid_adharcard: ' कृपया आधार कार्ड प्रविष्ट करा . ',
  txt_no_viewer_to_view_file: ' ही फाईल पाहणार्‍यांकडे नाही . ',
  txt_unable_to_create_channel: ' चॅनेल तयार करण्यात अक्षम . ',
  txt_shishya_list: ' शिष्य सूची ',
  no_notifications: 'सूचना डेटा उपलब्ध नाही . ',
  no_notifications_msg: 'सूचना डेटा उपलब्ध नाही . ',
  no_upcoming_session: ' कोणत्याही आगामी सत्र  नाही ',
  no_completed_session: ' कोणत्याही पूर्ण सत्र  नाही. ',
  no_certificate_message:
    'आपल्याकडे अद्याप प्रमाणपत्रे नाहीत. कृपया प्रमाणपत्र मिळविण्यासाठी एक कोर्स पूर्ण करा . ',
  no_expense_data: ' खर्चाचा डेटा उपलब्ध नाही . ',
  no_attendance_log: ' उपस्थिती लॉग उपलब्ध नाही . ',
  txt_new_message: ' कडून नवीन संदेश ',
  txt_welcome: ' आपले स्वागत आहे ',
  txt_data_not_available_leaderboard:
    'आपण लीडरबोर्डवरील पहिलेच आहात, त्वरा करा आणि आमची मूल्यांकन आता पास करा! ',
  txt_please_wait_for_internet_to_upload_bill:
    'आपण ऑफलाइन असता तेव्हा आपण बिल अपलोड करू शकत नाही. पुन्हा प्रयत्न करा . ',
  txt_ok: ' ठीक ',
  txt_time_over_message: ' वेळ संपला आहे . चांगले प्रयत्न . ',
  txt_record: ' रेकॉर्ड ',
  txt_stop_record: ' रेकॉर्डिंग थांबवा ',
  txt_play: ' प्ले ',
  txt_stop: ' थांबा ',
  txt_review_submitted: ' पुनरावलोकन सबमिट केले . ',
  txt_view_courses: ' पहा कोर्सेस ',
  txt_choose_country: 'देश  निवडा  ',
  txt_india: ' भारत ',
  txt_south_africa: ' दक्षिण आफ्रिका ',
  txt_sri_lanka: ' श्री लंका ',
  txt_bangladesh: ' बांगलादेश ',
  txt_indonesia: ' इंडोनेशिया ',
  txt_session_detail_updated: ' सत्राचे तपशील यशस्वीरित्या अद्यतनित केले . ',
  txt_session_download_success: ' सत्राचा तपशील यशस्वीरित्या डाउनलोड झाला . ',
  txt_article_updated: ' लेख तपशील यशस्वीरित्या अद्यतनित केला . ',
  txt_article_download: ' लेख तपशील यशस्वीरित्या डाउनलोड झाला . ',
  txt_video_updated: ' व्हिडिओ तपशील यशस्वीरित्या अद्यतनित केला . ',
  txt_video_download: ' व्हिडिओ तपशील यशस्वीरित्या डाउनलोड झाला . ',
  txt_course_updated: ' कोर्स तपशील यशस्वीरित्या अद्यतनित केला . ',
  txt_course_download: ' कोर्स तपशील यशस्वीरित्या डाउनलोड झाला . ',
  txt_no_expense_data_available_to_export:
    ' निर्यात करण्यासाठी कोणताही खर्च डेटा नाही . ',
  txt_no_attendance_to_export: 'निर्यात करण्यासाठी उपस्थिती डेटा नाही . ',
  txt_sync_started_with_server: ' सर्व्हरसह समक्रमण प्रारंभ झाले . ',
  txt_recording: ' रेकॉर्डिंग प्ले होत आहे . ',
  txt_recording_stopped: ' रेकॉर्डिंग थांबले . ',
  txt_recording_started: ' रेकॉर्डिंग प्रारंभ झाले . ',
  txt_please_complete_section:
    'कृपया पुढील अनलॉक करण्यासाठी विभाग पूर्ण करा . ',
  txt_pending_assessment: ' प्रलंबित मूल्यमापन ',
  txt_otp_retry_failed: 'ओटीपी पाठविणे अयशस्वी . ',
  txt_otp_retry_success: 'ओटीपी यशस्वीरित्या पाठविला . ',
  txt_invalid_otp: ' कृपया एक वैध ओटीपी प्रविष्ट करा . ',
  txt_unable_to_send_review: 'पुनरावलोकन सादर करण्यात अक्षम . ',
  txt_unable_to_submit_quiz: ' प्रश्न सबमिट करण्यात अक्षम . ',
  txt_no_assessment: 'आम्ही मूल्यांकन तपशील आणण्यात अक्षम आहोत . ',
  txt_no_data_available: ' कोणताही डेटा उपलब्ध नाही . ',
  txt_unable_to_register:
    'क्षमस्व आम्ही आपले खाते नोंदणी करण्यात अक्षम आहोत . ',
  txt_unable_to_update_account:
    'क्षमस्व आम्ही आपले तपशील अद्यतनित करण्यात अक्षम आहोत . ',
  txt_shishyas_course_watch_counter: ' %s शिष्यांनी हा कोर्स पाहिला आहे . ',
  txt_shishya_course_watch_counter: ' %s शिष्यांनी हा कोर्स पाहिला आहेच . ',
  txt_shishya_are_attending_session: ' %s शिष्य अधिवेशनात हजेरी लावत आहेत . ',
  txt_shishyas_are_attending_session: ' %s शिष्य अधिवेशनात हजेरी लावत आहेत . ',
  txt_profile_updated: ' प्रोफाइल यशस्वीरित्या अद्यतनित केले . ',
  txt_data_not_available_session: ' सत्र डेटा उपलब्ध नाही ',
  no_article_message: ' कोणताही लेख उपलब्ध नाही . ',
  no_course_message: ' कोणत्याही कोर्स उपलब्ध नाही . ',
  no_video_message: ' कोणत्याही व्हिडिओ उपलब्ध नाही ',
  txt_session_end_successfully: ' सत्र यशस्वीरित्या समाप्त झाले . ',
  txt_session_end_failed: 'सत्र समाप्त करण्यात अक्षम . ',
  txt_to_be_launched_soon: 'लवकरच सुरू होईल ',
  txt_you_can_not_start_day_again:
    " आपण पुन्हा \\'प्रारंभ दिवस\\' करू शकत नाही . ",
  txt_view_more: ' अधिक पहा ',
  txt_view_less: ' कमी पहा   ',
  txt_difficult_to_understand: 'समजण्यास अवघड.',
  txt_too_fast: 'खूप वेगवान.',
  txt_other: 'इतर',
  txt_shishya_already_added_session: 'हे शिष्य आधीच अधिवेशनात जोडले गेले आहे.',
  txt_no_match_found: 'कोणतीही जुळणी आढळली नाही.',
  txt_expenses_added_success: 'खर्च यशस्वीरित्या जोडला.',
  txt_expenses_added_failed: 'खर्च जोडण्यात अक्षम.',
  txt_shishya_already_added: 'शिष्य आधीच जोडले गेले आहे.',
  txt_shishya_have_attend_session: 'शिश्या या अधिवेशनात सहभागी झाली आहेत',
  txt_shishyas_have_attend_session: 'शिश्यानी या अधिवेशनात हजेरी लावली',
  txt_can_not_start_session_zero_shishya:
    'या सत्रामध्ये कोणतेही शिष्य जोडलेले नाही त्यामुळे आपण सत्र प्रारंभ करू शकत नाही.',
  txt_pending_assessment_message: 'कृपया पुढील %s अनलॉक करण्यासाठी %s पहा.',
  txt_it_seems_sanchalak:
    'असे दिसते आहे की आपले तपशील संचालक म्हणून नोंदणीकृत आहेत. कृपया प्रशासकाशी संपर्क साधा.',
  no_attended_session: 'उपस्थिती सत्र नाही.',
  txt_add_more_details: 'अधिक तपशील जोडा',
  txt_please_enter_valid_pincode: 'कृपया वैध पिन कोड प्रविष्ट करा',
  txt_please_enter_pincode: 'कृपया पिन कोड प्रविष्ट करा',
  txt_can_not_start_session_before_date:
    'आपण सत्राच्या तारखेपूर्वी सत्र प्रारंभ करू शकत नाही.',
  txt_video_not_available: 'व्हिडिओ उपलब्ध नाही.',
  txt_audio_not_available: 'ऑडिओ उपलब्ध नाही.',
  txt_file_not_available: 'फाईल उपलब्ध नाही.',
  font_size: [' लहान ', ' मध्यम ', ' मोठा ', ' अतिरिक्त मोठा '],
  occupation: [
    ' शेतकरी ',
    ' अकाउंटंट ',
    ' चालक ',
    ' क्लिनर ',
    ' बांधकाम मजूर ',
    ' विद्यार्थी ',
    'मच्छीमार',
    ' नर्स ',
    ' कार्यालयीन लिपिक ',
    ' विक्रेता ',
    ' शिवणकामाचे यंत्र ऑपरेटर ',
    ' दुकानदार ',
    ' टेलर ',
    ' शिक्षक ',
    ' भाजीपाला तोडणी करणारा ',
    ' भाजी निवडक ',
    ' वेटर ',
    ' इतर ',
  ],
  dependent: [
    ' 0 ',
    ' 1 ',
    ' 2 ',
    ' 3 ',
    ' 4 ',
    ' 5 ',
    ' 6 ',
    ' 7 ',
    ' 8 ',
    ' 9 ',
    '10 ',
  ],
  maritalstatus: ['विवाहित', 'अविवाहित'],
  mothertonge: ['हिंदी', 'इंग्रजी', 'गुजराती', 'मराठी', 'इतर'],
  expense_category: ['प्रवास', 'अन्न', 'इतर'],
};
