/*
 *
 * Profile constants
 *
 */

export const UPLOAD_PENDING = 'UPLOAD_PENDING';
export const UPLOAD_FULFILLED = 'UPLOAD_FULFILLED';
export const UPLOAD_REJECTED = 'UPLOAD_REJECTED';

export const PROFILE_UPDATE = 'PROFILE_UPDATE';
export const PROFILE_UPDATE_PENDING = 'PROFILE_UPDATE_PENDING';
export const PROFILE_UPDATE_FULFILLED = 'PROFILE_UPDATE_FULFILLED';
export const PROFILE_UPDATE_REJECTED = 'PROFILE_UPDATE_REJECTED';
