/*
 *
 * Videos constants
 *
 */

export const VIDEOS = 'VIDEOS';
export const VIDEOS_PENDING = 'VIDEOS_PENDING';
export const VIDEOS_FULFILLED = 'VIDEOS_FULFILLED';
export const VIDEOS_REJECTED = 'VIDEOS_REJECTED';

export const VIDEOS_DETAILS_PENDING = 'VIDEOS_DETAILS_PENDING';
export const VIDEOS_DETAILS_FULFILLED = 'VIDEOS_DETAILS_FULFILLED';
export const VIDEOS_DETAILS_REJECTED = 'VIDEOS_DETAILS_REJECTED';

export const SEND_COMMENT_PENDING = 'SEND_COMMENT_PENDING';
export const SEND_COMMENT_FULFILLED = 'SEND_COMMENT_FULFILLED';
export const SEND_COMMENT_REJECTED = 'SEND_COMMENT_REJECTED';
