/*
 *
 * Sessions constants
 *
 */

export const UPC_SESION = 'UPC_SESION';
export const UPC_SESION_PENDING = 'UPC_SESION_PENDING';
export const UPC_SESION_FULFILLED = 'UPC_SESION_PENDING_FULFILLED';
export const UPC_SESION_REJECTED = 'UPC_SESION_PENDING_REJECTED';
