/*
 *
 * Sessions constants
 *
 */

export const UPC_SESION = 'UPC_SESION';
export const UPC_SESION_PENDING = 'UPC_SESION_PENDING';
export const UPC_SESION_FULFILLED = 'UPC_SESION_PENDING_FULFILLED';
export const UPC_SESION_REJECTED = 'UPC_SESION_PENDING_REJECTED';

export const ATT_SESION_PENDING = 'ATT_SESION_PENDING';
export const ATT_SESION_FULFILLED = 'ATT_SESION_PENDING_FULFILLED';
export const ATT_SESION_REJECTED = 'ATT_SESION_PENDING_REJECTED';

export const SESSION_DETAILS_PENDING = 'SESSION_DETAILS_PENDING';
export const SESSION_DETAILS_FULFILLED = 'SESSION_DETAILS_PENDING_FULFILLED';
export const SESSION_DETAILS_REJECTED = 'SESSION_DETAILS_PENDING_REJECTED';
