/*
 *
 * Certificates constants
 *
 */

export const CERTIFICATE = 'CERTIFICATE';
export const CERTIFICATE_PENDING = 'CERTIFICATE_PENDING';
export const CERTIFICATE_FULFILLED = 'CERTIFICATE_FULFILLED';
export const CERTIFICATE_REJECTED = 'CERTIFICATE_REJECTED';
