/**
 * DEVELOPMENT WEBPACK CONFIGURATION
 */

const path = require('path');
const webpack = require('webpack');
const appLocation = path.resolve(__dirname, '../../app');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CircularDependencyPlugin = require('circular-dependency-plugin');

module.exports = require('./webpack.base.babel')({
  mode: 'development',

  // Add hot reloading in development
  entry: [
    require.resolve('react-app-polyfill/ie11'),
    'webpack-hot-middleware/client?reload=true',
    path.join(process.cwd(), 'app/app.js'), // Start with js/app.js
  ],

  // Don't use hashes in dev mode for better performance
  output: {
    filename: '[name].js',
    chunkFilename: '[name].chunk.js',
  },

  optimization: {
    splitChunks: {
      chunks: 'all',
    },
  },

  // Add development plugins
  plugins: [
    new webpack.HotModuleReplacementPlugin(), // Tell webpack we want hot reloading
    new HtmlWebpackPlugin({
      inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
      template: 'app/index.html',
    }),
    new CircularDependencyPlugin({
      exclude: /a\.js|node_modules/, // exclude node_modules
      failOnError: false, // show a warning when there is a circular dependency
    }),
  ],

  // Emit a source map for easier debugging
  // See https://webpack.js.org/configuration/devtool/#devtool
  resolve: {
    alias: {
      DataService: path.resolve(path.join(appLocation, '/dataService')),
      Model: path.resolve(path.join(appLocation, '/model')),
      Component: path.resolve(path.join(appLocation, '/components')),
      Containers: path.resolve(path.join(appLocation, '/containers')),
      Image: path.resolve(path.join(appLocation, '/images')),
      Constant: path.resolve(path.join(appLocation, '/constants')),
      Service: path.resolve(path.join(appLocation, '/services')),
      Config: path.resolve(path.join(appLocation, '/config')),
      Global: path.resolve(path.join(appLocation, '/common')),
    },
    modules: ['app', 'node_modules'],
    extensions: ['.js', '.jsx', '.react.js'],
    mainFields: ['browser', 'jsnext:main', 'main'],
  },

  devtool: 'eval-source-map',

  performance: {
    hints: false,
  },
});
